# Freestanding Capstone ABI. This existing port supplies its own libc headers.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR capstone64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PG_PLATFORM capstone-domain CACHE STRING "Execution platform" FORCE)
include("${CMAKE_CURRENT_LIST_DIR}/../Workspace.cmake")
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/../../../../.." ABSOLUTE)
pg_path(CAPSTONE_LLVM_BUILD_DIR "${repo}/llvm/cmake-build-debug" "Capstone compiler build")
set(CMAKE_C_COMPILER "${CAPSTONE_LLVM_BUILD_DIR}/bin/clang")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_C_COMPILER_TARGET capstone64-unknown-elf)
set(CMAKE_ASM_COMPILER_TARGET capstone64-unknown-elf)
set(CMAKE_AR "${CAPSTONE_LLVM_BUILD_DIR}/bin/llvm-ar")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_AR> s <TARGET>")
set(CMAKE_LINKER "${CAPSTONE_LLVM_BUILD_DIR}/bin/ld.lld")
set(CMAKE_C_FLAGS_INIT "-Xclang -target-feature -Xclang +m -ffreestanding -fno-builtin -nostdlibinc")
set(CMAKE_ASM_FLAGS_INIT "--target=capstone64-unknown-elf -ffreestanding")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CAPSTONE_LLVM_BUILD_DIR)
