#!/usr/bin/env python3
"""Is the Capstone toolchain BINARY up to date with the compiler SOURCE it sits next to?

Why this exists (2026-09-05, C-44): dev was fast-forwarded onto a branch that changed the
jump-table lowering AND, in the same range, retired the `-fno-jump-tables` pin from the
SQLite build scripts. The main checkout's llvm/cmake-build-debug had last been built the
evening before. Running the new script with the old binary produced an image whose 26 jump
tables used the pre-change integer dispatch, which faults on every corpus file -- and it was
filed as a compiler defect in the new lowering, with a bisection that held "the compiler
binary" constant without asking which binary it was. A script change and a compiler change
that land together are only consistent together.

Definition. ninja's own dependency graph is asked (a dry run, ~0.5 s) what it would do for
the targets we actually use (llc, clang, lld -- ld.lld is a symlink the lld target creates,
not a target). The answer is classified:
  fresh          nothing pending
  fresh-relink   every pending step is part of the VCS-revision chain: a commit touches
                 .git/logs/HEAD, which regenerates VCSRevision.h / VCSVersion.inc, recompiles
                 the handful of objects embedding it (AsmPrinter, LTO, IRSymtab, the two
                 Version.cpp) and relinks; the code is the same
  STALE          any other compile or tablegen step is pending: a compiler source is newer
                 than its object, or a .td newer than its .inc

Exit status: 0 fresh / fresh-relink, 1 STALE, 2 cannot check (no ninja, no build dir,
ninja failed). "cannot check" is an error on purpose: silence must never read as fresh.
Identity is printed either way (CodeGen .so hash + mtime, clang's embedded revision) so a
result row can carry it.

Usage: toolchain-fresh.py [--build DIR] [--targets llc clang ld.lld] [--quiet-if-fresh]
  --build defaults to $CAPSTONE_LLVM_BUILD_DIR, else the parent of $CAPSTONE_LLVM_BIN.
"""
import argparse, hashlib, os, re, shutil, subprocess, sys, time

# Objects that embed the VCS revision and are legitimately recompiled after every commit.
VCS_OBJECTS = ('AsmPrinter/AsmPrinter.cpp.o', 'lib/LTO/LTO.cpp.o', 'Object/IRSymtab.cpp.o',
               'clang/lib/Basic/Version.cpp.o', 'lld/Common/Version.cpp.o')
VCS_GENERATED = ('VCSRevision.h', 'VCSVersion.inc')

# Every binary the Capstone lit suites actually invoke, not just the compiler.
#
# THIS LIST USED TO BE ('llc', 'clang', 'lld'), AND THAT WAS A HOLE IN THE GATE ITSELF.
# This is a shared-library build, so a partial rebuild leaves llc fresh while the tools a test
# pipes into are not. Measured 2026-09-10 after a merge: rebuilding only llc/clang/lld/llvm-mc
# left llvm-readelf at its six-day-old build, and MC/Capstone/obj-relocs-cap-constant.ll failed
# with `Machine: 103` -- EM_CR, an unrelated vendor's e_machine -- which reads as an object-writer
# defect in whatever was merged last rather than as a stale reader. This gate reported FRESH
# throughout, because it only ever asked ninja about those three targets.
#
# A PARTIAL REBUILD IS WORSE THAN NO REBUILD. No rebuild leaves a consistently old toolchain whose
# failures are attributable to being old; a partial one leaves an INCONSISTENT toolchain whose
# failures point at whatever changed most recently -- after a merge, someone else's work.
#
# Tell for this class, worth knowing: a backend that got its own e_machine wrong would emit a wrong
# value of its own family, or zero. It would never emit another vendor's specific, valid identifier.
# A nonsensical-but-valid-elsewhere constant means a stale reader, not a live defect.
DEFAULT_TARGETS = ('llc', 'clang', 'lld', 'llvm-mc', 'llvm-readobj',
                   'llvm-objdump', 'llvm-objcopy', 'llvm-nm', 'FileCheck', 'not', 'split-file')
# NOT in the list, deliberately: llvm-readelf. It is a SYMLINK that ninja regenerates with a
# `Generating ../../bin/llvm-readelf` step, which the classifier below cannot tell from real work --
# and it is regenerated by the VCS cascade itself (a commit rewrites VCSRevision.h -> IRSymtab.cpp.o
# -> libLLVMObject.so -> llvm-readobj -> this symlink). Naming it made the gate report STALE on a
# clean tree after EVERY COMMIT. A gate that always cries stale gets overridden, and then the hole it
# was written for is open again, so this was worse than the bug it replaced. Its real target,
# llvm-readobj, IS checked, which is what actually matters; TOOL_TARGET maps the name.

# Scanned to keep DEFAULT_TARGETS honest as the tests change; see drift_check.
SUITE_DIRS = ('llvm/test/MC/Capstone', 'llvm/test/CodeGen/Capstone',
              'llvm/test/MC/Disassembler/Capstone')

# The lit suites are not the only consumer. llvm-objcopy and llvm-nm are invoked by the ladder and
# glue scripts -- gen-gp-captable-glue.py builds the cap table every silicon image is linked
# against -- so they sit ON the artifact path, not beside it. A stale one mishandling Capstone
# objects is the same family as the stale reader that started all this, and it would surface as a
# bad image rather than a failed test. These are scanned for tool names too; they are shell and
# python rather than lit, so there are no RUN lines and no substitutions to resolve.
# Scoped to the directories that BUILD DOMAIN IMAGES, not all of capstone/tests. Widening it to
# the whole tree pulls in developer tooling -- llvm-reduce from reduce.sh, llvm-stress from the
# fuzz harness, a cheribuild target that merely looks like an llvm binary -- and demanding those be
# built before any run is both heavy and unrelated to whether an ARTIFACT is sound. Measured while
# writing this: the wide glob made the gate refuse on five such names, one of which was llvm-dwarfdump
# appearing only in this file's own docstring.
SCRIPT_DIRS = ('capstone/tests/runtime-qemu', 'capstone/tests/rtl-smoke')
SCRIPT_SUFFIXES = ('.sh', '.py')
RUN_TOOL_RE = re.compile(r'\b(llc|clang|ld\.lld|lld|llvm-[a-z0-9-]+|FileCheck|split-file|not)\b')
# Lit SUBSTITUTIONS defeat a plain tool-name scan: `%llc_cap` carries an underscore, so no
# tool-name alternation can see it, and the audit of 80f28127e895 showed the drift check silently
# blind to it. Custom substitutions are resolved from the lit configs below; an unresolved one is
# an ERROR, not something to skip, because skipping it is how the coverage hole reopens quietly.
# In a script a tool name is only interesting when it is INVOKED. Requiring a quote, a path
# separator or a bare word-start immediately before it keeps a tool mentioned in prose out of the
# coverage set, which would otherwise force it into DEFAULT_TARGETS and make the gate refuse.
SCRIPT_TOOL_RE = re.compile(r'(?:[/"\'(]|^|\s)(llvm-[a-z0-9-]+|FileCheck)\b', re.M)
SUBST_RE = re.compile(r'%[A-Za-z_][A-Za-z0-9_]*')
# Lit builtins that never name a tool.
SUBST_BUILTIN = {'%s', '%S', '%t', '%T', '%p', '%m', '%basename_s'}
SUBST_DEF_RE = re.compile(r"""\(\s*r?['"](%[A-Za-z_][A-Za-z0-9_]*)['"]\s*,\s*r?['"]([^'"]*)['"]""")


def resolve_substitutions(repo_root, suites):
    """Map custom lit substitutions to the tools they expand to, from the suites' lit configs."""
    out = {}
    for rel in suites:
        d = os.path.join(repo_root, rel)
        for cfg in ('lit.local.cfg', 'lit.cfg.py', 'lit.cfg'):
            f = os.path.join(d, cfg)
            if not os.path.isfile(f):
                continue
            try:
                text = open(f, 'r', errors='ignore').read()
            except OSError:
                continue
            for name, repl in SUBST_DEF_RE.findall(text):
                out.setdefault(name, set()).update(RUN_TOOL_RE.findall(repl))
    return out


def run_lines(path):
    """RUN lines, with backslash continuations joined.

    Without joining, a tool on a continuation line is invisible: the audit demonstrated a two-line
    form, llc piped into llvm-dwarfdump with the break after the backslash, passing the drift check
    while the identical single-line form correctly refused it.
    """
    joined, pending = [], None
    try:
        with open(path, 'r', errors='ignore') as fh:
            for raw in fh:
                line = raw.rstrip('\n')
                if pending is not None:
                    pending += ' ' + line.lstrip(';# \t')
                elif 'RUN:' in line:
                    pending = line.split('RUN:', 1)[1]
                else:
                    continue
                if pending.rstrip().endswith('\\'):
                    pending = pending.rstrip()[:-1]
                else:
                    joined.append(pending)
                    pending = None
    except OSError:
        return []
    if pending is not None:
        joined.append(pending)
    return joined
# Aliases: the tool a test runs vs the ninja target that builds it.
TOOL_TARGET = {'ld.lld': 'lld', 'llvm-readelf': 'llvm-readobj'}


def drift_check(repo_root, suites, targets):
    """Tools the suites invoke that `targets` does not cover.

    Returns a list of uncovered tool names (empty when fully covered), or the string 'no-suite'
    when no suite directory exists. 'no-suite' is an ERROR at the call site rather than a pass:
    the root is derived from __file__, so a copied or relocated script would otherwise disable the
    whole drift check and still report fresh -- no data rendered as a pass, which is the exact rule
    this script is written to.
    """
    # found_suite tracks the LIT scan alone. A present script dir must not mask an absent suite
    # dir, or --suite pointing nowhere silently disables half the drift check and still reports fresh.
    seen, unresolved, found_suite = set(), set(), False
    subs = resolve_substitutions(repo_root, suites)
    for rel in suites:
        d = os.path.join(repo_root, rel)
        if not os.path.isdir(d):
            continue
        found_suite = True
        for dirpath, _, names in os.walk(d):
            for n in names:
                if n.startswith('lit.'):
                    continue
                for line in run_lines(os.path.join(dirpath, n)):
                    seen.update(RUN_TOOL_RE.findall(line))
                    for tok in SUBST_RE.findall(line):
                        if tok in SUBST_BUILTIN:
                            continue
                        if tok in subs:
                            seen.update(subs[tok])
                        else:
                            unresolved.add(tok)
    # Second source: the build/ladder scripts. Match only tool names that appear as an
    # INVOCATION -- preceded by a path separator, a quote, or the start of a word after $( or a
    # shell/py call -- so a tool merely NAMED in a comment does not force it into the target list.
    for rel in SCRIPT_DIRS:
        d = os.path.join(repo_root, rel)
        if not os.path.isdir(d):
            continue
        for dirpath, _, names in os.walk(d):
            for n in names:
                if not n.endswith(SCRIPT_SUFFIXES) or n == os.path.basename(__file__):
                    continue
                try:
                    text = open(os.path.join(dirpath, n), 'r', errors='ignore').read()
                except OSError:
                    continue
                seen.update(SCRIPT_TOOL_RE.findall(text))
    if not found_suite:
        return 'no-suite'
    covered = set(targets)
    missing = {t for t in seen if TOOL_TARGET.get(t, t) not in covered}
    # An unresolved substitution is reported like an uncovered tool: it may expand to anything.
    return sorted(missing | {f'{u} (unresolved substitution)' for u in unresolved})


def identity(build):
    so = os.path.join(build, 'lib', 'libLLVMCapstoneCodeGen.so')
    try:
        st = os.stat(so)
        h = hashlib.sha256(open(so, 'rb').read()).hexdigest()[:16]
        ident = f'libLLVMCapstoneCodeGen.so {h} built {time.strftime("%Y-%m-%d %H:%M", time.localtime(st.st_mtime))}'
    except OSError:
        ident = 'libLLVMCapstoneCodeGen.so MISSING'
    try:
        v = subprocess.run([os.path.join(build, 'bin', 'clang'), '--version'], capture_output=True,
                           text=True, timeout=30).stdout
        m = re.search(r'\b([0-9a-f]{40})\b', v)
        ident += f'; clang embeds {m.group(1)[:12]}' if m else '; clang embeds no revision'
    except (OSError, subprocess.TimeoutExpired):
        ident += '; clang not runnable'
    return ident


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--build', default=os.environ.get('CAPSTONE_LLVM_BUILD_DIR') or
                    (os.path.dirname(os.environ['CAPSTONE_LLVM_BIN'].rstrip('/'))
                     if os.environ.get('CAPSTONE_LLVM_BIN') else None))
    ap.add_argument('--targets', nargs='+', default=list(DEFAULT_TARGETS))
    ap.add_argument('--suite', nargs='+', default=None,
                    help='lit dirs whose RUN lines are scanned for tools not covered by --targets')
    ap.add_argument('--no-drift-check', action='store_true')
    ap.add_argument('--quiet-if-fresh', action='store_true')
    a = ap.parse_args()
    if not a.build or not os.path.isfile(os.path.join(a.build, 'build.ninja')):
        print(f'toolchain-fresh: cannot check: no build.ninja under {a.build!r}', file=sys.stderr)
        return 2
    if not a.no_drift_check:
        root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        missing = drift_check(root, a.suite or SUITE_DIRS, a.targets)
        if missing == 'no-suite':
            print('toolchain-fresh: cannot check: no lit suite directory found under '
                  f'{root!r}; the drift check cannot run, and silence must not read as '
                  'fresh. Pass --suite, or --no-drift-check if that is deliberate.',
                  file=sys.stderr)
            return 2
        if missing:
            print('toolchain-fresh: cannot check: the lit suites or build scripts invoke tools this gate '
                  f'does not verify: {" ".join(missing)}. Add them to DEFAULT_TARGETS (or pass '
                  '--targets); '
                  'reporting fresh without them is how a stale reader reads as a codegen bug.',
                  file=sys.stderr)
            return 2
    if not shutil.which('ninja'):
        print('toolchain-fresh: cannot check: ninja not on PATH', file=sys.stderr)
        return 2
    try:
        r = subprocess.run(['ninja', '-C', a.build, '-n', *a.targets], capture_output=True, text=True, timeout=120)
    except (subprocess.TimeoutExpired, OSError) as e:
        print(f'toolchain-fresh: cannot check: ninja dry run failed: {e}', file=sys.stderr)
        return 2
    if r.returncode != 0:
        print(f'toolchain-fresh: cannot check: ninja -n rc={r.returncode}: {r.stderr.strip()[:200]}', file=sys.stderr)
        return 2
    steps = [m.group(1) for m in re.finditer(r'^\[\d+/\d+\] (.*)$', r.stdout, re.M)]
    offending = []
    for s in steps:
        if s.startswith('Linking') or s.startswith('Creating') or s.startswith('Re-running'):
            continue
        if s.startswith('Generating') and s.endswith(VCS_GENERATED):
            continue
        # ninja prints objects as <dir>/CMakeFiles/<target>.dir/<file>.o; drop the CMakeFiles
        # segment before matching, or the revision-chain objects never match and every commit
        # without a rebuild reads STALE (it did, 2026-09-07: AsmPrinter/LTO/IRSymtab/Version).
        if s.startswith('Building') and re.sub(r'CMakeFiles/[^/]+\.dir/', '', s).endswith(VCS_OBJECTS):
            continue
        offending.append(s)
    ident = identity(a.build)
    if offending:
        print(f'toolchain-fresh: STALE: {a.build}\n  {ident}\n  {len(steps)} ninja steps pending, '
              f'{len(offending)} of them compile/tablegen outside the revision chain, e.g.:', file=sys.stderr)
        for s in offending[:6]:
            print('    ' + re.sub(r'CMakeFiles/[^ ]*\.dir/', '', s)[:110], file=sys.stderr)
        print(f'  rebuild before producing any artifact: ninja -j90 -C {a.build} ' + ' '.join(a.targets)
              + '\n  (never while a QEMU suite or twin run is in flight)', file=sys.stderr)
        return 1
    if not a.quiet_if_fresh:
        note = f' ({len(steps)} pending steps are revision-chain relinks only)' if steps else ''
        print(f'toolchain-fresh: fresh: {ident}{note}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
