#!/usr/bin/env bash
# Install the two random-program generators the Tier 2c differential uses, under
# $HOME/opt, pinned, idempotent.  Records what was built in TOOLS.lock next to this
# script, and VERIFIES the flag spellings the campaign relies on rather than assuming
# them -- a generator that silently ignores an unknown flag would run a different
# campaign from the one described.
#
#   setup-fuzz-tools.sh            build what is missing
#   setup-fuzz-tools.sh --force    rebuild both
set -euo pipefail
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PREFIX=${FUZZ_TOOLS_PREFIX:-$HOME/opt}
SRC="$PREFIX/src"
LOCK="$SCRIPT_DIR/TOOLS.lock"
FORCE=${1:-}
mkdir -p "$SRC"
JOBS=$(( $(nproc) * 7 / 10 )); [ "$JOBS" -lt 1 ] && JOBS=1

# Pins: the branch heads observed 2026-09-04; a rebuild fetches the same commits.
CSMITH_REPO=https://github.com/csmith-project/csmith.git
CSMITH_REF=${CSMITH_REF:-master}
YARPGEN_REPO=https://github.com/intel/yarpgen.git
YARPGEN_REF=${YARPGEN_REF:-main}

clone() {  # repo ref dir
  if [[ -d "$3/.git" ]]; then git -C "$3" fetch -q origin "$2"; git -C "$3" checkout -q FETCH_HEAD
  else git clone -q "$1" "$3"; git -C "$3" checkout -q "$2" 2>/dev/null || git -C "$3" checkout -q "origin/$2"; fi
  git -C "$3" rev-parse HEAD
}

if [[ ! -x "$PREFIX/csmith/bin/csmith" || "$FORCE" == "--force" ]]; then
  echo "== csmith"
  CS=$(clone "$CSMITH_REPO" "$CSMITH_REF" "$SRC/csmith")
  rm -rf "$SRC/csmith/build"; mkdir -p "$SRC/csmith/build"
  ( cd "$SRC/csmith/build" && cmake -DCMAKE_INSTALL_PREFIX="$PREFIX/csmith" -DCMAKE_BUILD_TYPE=Release .. > cmake.log 2>&1 \
      && make -j"$JOBS" > make.log 2>&1 && make install > install.log 2>&1 ) \
    || { echo "ERROR: csmith build failed; see $SRC/csmith/build/*.log" >&2; exit 1; }
else
  CS=$(git -C "$SRC/csmith" rev-parse HEAD 2>/dev/null || echo unknown)
fi

if [[ ! -x "$PREFIX/yarpgen/bin/yarpgen" || "$FORCE" == "--force" ]]; then
  echo "== yarpgen"
  YG=$(clone "$YARPGEN_REPO" "$YARPGEN_REF" "$SRC/yarpgen")
  rm -rf "$SRC/yarpgen/build"; mkdir -p "$SRC/yarpgen/build"
  ( cd "$SRC/yarpgen/build" && cmake -DCMAKE_BUILD_TYPE=Release .. > cmake.log 2>&1 && make -j"$JOBS" > make.log 2>&1 ) \
    || { echo "ERROR: yarpgen build failed; see $SRC/yarpgen/build/*.log" >&2; exit 1; }
  mkdir -p "$PREFIX/yarpgen/bin"; cp -f "$SRC/yarpgen/build/yarpgen" "$PREFIX/yarpgen/bin/yarpgen"
else
  YG=$(git -C "$SRC/yarpgen" rev-parse HEAD 2>/dev/null || echo unknown)
fi

# VERIFY the flag spellings the campaign uses.  Each must appear in the tool's own
# help text; a missing one is an error here, not a silently different campaign later.
CSMITH="$PREFIX/csmith/bin/csmith"
CSH=$("$CSMITH" --help 2>&1 || true)
for f in --seed --no-argc --no-float --no-unions --no-packed-struct --max-array-dim --max-funcs --builtins --no-safe-math; do
  grep -q -- "$f" <<< "$CSH" || { echo "ERROR: csmith does not document $f" >&2; exit 1; }
done
CSMITH_INC=$(dirname "$(find "$PREFIX/csmith/include" -name csmith.h | head -1)" 2>/dev/null)
[[ -f "$CSMITH_INC/csmith.h" ]] || { echo "ERROR: csmith runtime header not found under $PREFIX/csmith/include" >&2; exit 1; }

YARPGEN="$PREFIX/yarpgen/bin/yarpgen"
YGH=$("$YARPGEN" --help 2>&1 || true)
for f in --seed --std -o; do
  grep -q -- "$f" <<< "$YGH" || { echo "ERROR: yarpgen does not document $f" >&2; exit 1; }
done
YG_STD_C=$(grep -o 'c\b' <<< "$(grep -- '--std' <<< "$YGH")" | head -1 || true)

{
  echo "# generated by setup-fuzz-tools.sh on $(date -Is); do not edit"
  echo "csmith_repo=$CSMITH_REPO"
  echo "csmith_commit=$CS"
  echo "csmith_bin=${CSMITH/#$HOME/\$HOME}"
  echo "csmith_version=$("$CSMITH" --version 2>&1 | head -1)"
  echo "csmith_include=${CSMITH_INC/#$HOME/\$HOME}"
  echo "yarpgen_repo=$YARPGEN_REPO"
  echo "yarpgen_commit=$YG"
  echo "yarpgen_bin=${YARPGEN/#$HOME/\$HOME}"
  echo "yarpgen_version=$("$YARPGEN" --version 2>&1 | head -1)"
  echo "yarpgen_std_line=$(grep -- '--std' <<< "$YGH" | head -1 | tr -s ' ')"
} > "$LOCK"
echo "== fuzz tools ready"; cat "$LOCK"
