add_library(replay-options INTERFACE)
target_link_libraries(replay-options INTERFACE Capstone::Runtime region-options)
target_include_directories(replay-options INTERFACE
  "${PROJECT_SOURCE_DIR}/src/shared" "${PROJECT_SOURCE_DIR}/src/allocators/sublet"
  "${PROJECT_SOURCE_DIR}/src/capstone-domain")
target_compile_options(replay-options INTERFACE
  "$<$<COMPILE_LANGUAGE:C>:-ffunction-sections;-fdata-sections>")
option(PG_MEMORY_PROFILE "Collect allocator memory snapshots in QEMU replay" OFF)
option(PG_SEPARATE_SCRATCH "Give both replay arms a separate identity-table region" ${PG_MEMORY_PROFILE})
if(PG_SEPARATE_SCRATCH)
  target_compile_definitions(replay-options INTERFACE PG_SEPARATE_SCRATCH)
endif()
if(PG_MEMORY_PROFILE)
  if(NOT PORT_PLATFORM STREQUAL "capstone-domain")
    message(FATAL_ERROR "Memory profiling is a QEMU domain configuration")
  endif()
  if(NOT PG_SEPARATE_SCRATCH)
    message(FATAL_ERROR "Memory profiles require separate replay scratch in both arms")
  endif()
  target_compile_definitions(replay-options INTERFACE PG_MEMORY_PROFILE)
  target_include_directories(replay-options INTERFACE "${PROJECT_SOURCE_DIR}/src/capstone-domain/memory")
endif()
option(PG_CHECK_DATA "Write/check payloads at free and realloc" ON)
if(PG_CHECK_DATA)
  target_compile_definitions(replay-options INTERFACE REPLAY_CHECK_DATA)
endif()

function(pg_manager name mode)
  if(mode STREQUAL "native")
    set(aset "${PG_SOURCE}/src/backend/utils/mmgr/aset.c")
  else()
    set(aset "${CMAKE_BINARY_DIR}/variants/${mode}/aset.c")
  endif()
  add_library(${name} OBJECT "${aset}" src/shared/postgres-compat.c)
  foreach(file mcxt generation slab bump alignedalloc memdebug)
    if(mode STREQUAL "sublet" AND file MATCHES "^(generation|slab|bump)$")
      target_sources(${name} PRIVATE "${CMAKE_BINARY_DIR}/variants/sublet/${file}.c")
    else()
      target_sources(${name} PRIVATE "${PG_SOURCE}/src/backend/utils/mmgr/${file}.c")
    endif()
  endforeach()
  target_link_libraries(${name} PUBLIC replay-options)
  if(NOT mode STREQUAL "native")
    target_include_directories(${name} PUBLIC "${CMAKE_BINARY_DIR}/variants/${mode}/include")
  endif()
  target_include_directories(${name} PUBLIC "${PG_SOURCE}/src/include" "${PG_SOURCE}/src/backend")
endfunction()

if(PORT_HOSTED)
  if(PORT_PLATFORM STREQUAL "cheribsd")
    # The existing capability-layout variant has 16-byte chunks/free links.
    # Retain its ABI changes without enabling Sublet lifetime hooks.
    pg_manager(manager-native spatial)
    file(READ "${CMAKE_BINARY_DIR}/variants/spatial/include/pg_config.h" cheri_config)
    string(REPLACE "#define SIZEOF_VOID_P 8" "#define SIZEOF_VOID_P 16"
      cheri_config "${cheri_config}")
    file(WRITE "${CMAKE_BINARY_DIR}/cheribsd-include/pg_config.h" "${cheri_config}")
    target_include_directories(manager-native BEFORE PUBLIC
      "${CMAKE_BINARY_DIR}/cheribsd-include")
  else()
    pg_manager(manager-native native)
  endif()
  add_library(postgres-contexts STATIC src/native/replay/printf.c)
  target_link_libraries(postgres-contexts PUBLIC manager-native)
  add_library(PostgreSQL::MemoryContexts ALIAS postgres-contexts)
  add_executable(allocator-example examples/contexts.c)
  target_link_libraries(allocator-example PRIVATE PostgreSQL::MemoryContexts)
  include("${PORT_SUPPORT_ROOT}/cmake/Client.cmake")
  port_add_client(PostgreSQL::MemoryContexts)
  if(PORT_PLATFORM STREQUAL "cheribsd")
    set(hosted_entry src/cheribsd/main.c)
  else()
    set(hosted_entry src/native/replay/main.c)
  endif()
  add_executable(replay ${hosted_entry} src/native/replay/printf.c src/shared/replay-engine.c)
  target_link_libraries(replay PRIVATE manager-native)
  target_link_options(replay PRIVATE LINKER:--gc-sections)
  add_executable(contexts-native tests/contexts-native.c src/native/replay/printf.c)
  target_link_libraries(contexts-native PRIVATE manager-native)
  target_link_options(contexts-native PRIVATE LINKER:--gc-sections)
  add_test(NAME contexts-native COMMAND contexts-native)
  set_tests_properties(contexts-native PROPERTIES LABELS native TIMEOUT 60)
else()
  enable_language(ASM)
  target_include_directories(replay-options SYSTEM INTERFACE "${PROJECT_SOURCE_DIR}/src/capstone-domain/include")
  pg_manager(manager-spatial spatial)
  pg_manager(manager-sublet sublet)
  set(domain_sources src/capstone-domain/domain-runtime.c src/capstone-domain/printf.c
    "${CAPSTONE_REPO_ROOT}/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c")
  function(pg_domain name)
    add_executable(${name} ${ARGN} ${domain_sources})
    target_link_libraries(${name} PRIVATE replay-options)
    capstone_configure_domain(${name}
      DATA_BYTES ${PG_DOMAIN_STACK_BYTES} STACK_BYTES ${PG_DOMAIN_STACK_BYTES})
    add_custom_command(TARGET ${name} POST_BUILD
      COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/cmake/check-domain.py" "$<TARGET_FILE:${name}>")
  endfunction()
  pg_domain(replay-spatial src/allocators/spatial/replay.c src/allocators/spatial/backing-allocator.c
    src/capstone-domain/string.c src/shared/replay-engine.c)
  target_link_libraries(replay-spatial PRIVATE manager-spatial)
  pg_domain(replay-sublet src/allocators/sublet/replay.c src/allocators/sublet/context-pools.c src/allocators/sublet/unsupported-allocators.c
    src/capstone-domain/string.c src/shared/replay-engine.c)
  target_link_libraries(replay-sublet PRIVATE manager-sublet)
  if(PG_MEMORY_PROFILE)
    if(NOT PG_CHECK_DATA)
      message(FATAL_ERROR "Memory profiles require the replay's length and payload checks")
    endif()
    target_sources(replay-spatial PRIVATE src/capstone-domain/memory/profile.c)
    target_sources(replay-sublet PRIVATE src/capstone-domain/memory/profile.c)
  endif()
  pg_domain(context-hierarchy security-tests/capstone/context-hierarchy.c src/allocators/sublet/context-pools.c
    src/allocators/sublet/unsupported-allocators.c src/capstone-domain/string.c)
  target_link_libraries(context-hierarchy PRIVATE manager-sublet)
  target_compile_definitions(context-hierarchy PRIVATE "PG_DOM_FAIL_MARKER=\"__CAPSTONE_PG_HIER_FAILED__\\n\"")
  pg_domain(subpool-lifetimes security-tests/capstone/subpool-lifetimes.c src/allocators/sublet/context-pools.c)
  target_compile_definitions(subpool-lifetimes PRIVATE "PG_DOM_FAIL_MARKER=\"__CAPSTONE_PG_SUBPOOL_FAILED__\\n\"")
  # A seam, not a case: bug-corpora supplies the defect program, the port only
  # builds it the same way it builds its own fixtures. Case material must not
  # live inside a port (docs/design/repo-layout.md).
  set(PG_CORPUS_SRC "" CACHE FILEPATH "Corpus-supplied domain defect program")
  if(PG_CORPUS_SRC)
    foreach(mode spatial sublet)
      pg_domain(defects-${mode} "${PG_CORPUS_SRC}" src/capstone-domain/string.c)
      target_link_libraries(defects-${mode} PRIVATE manager-${mode})
      if(mode STREQUAL "sublet")
        target_compile_definitions(defects-${mode} PRIVATE PG_DEFECTS_SUBLET)
        target_sources(defects-${mode} PRIVATE src/allocators/sublet/context-pools.c
          src/allocators/sublet/unsupported-allocators.c)
      else()
        target_sources(defects-${mode} PRIVATE src/allocators/spatial/backing-allocator.c)
      endif()
    endforeach()
  endif()
  foreach(mode spatial sublet)
    pg_domain(contexts-${mode} security-tests/capstone/contexts.c src/capstone-domain/string.c)
    target_include_directories(contexts-${mode} PRIVATE "${PROJECT_SOURCE_DIR}/tests")
    target_link_libraries(contexts-${mode} PRIVATE manager-${mode})
    if(mode STREQUAL "sublet")
      target_compile_definitions(contexts-${mode} PRIVATE PG_CONTEXTS_SUBLET)
      target_sources(contexts-${mode} PRIVATE src/allocators/sublet/context-pools.c
        src/allocators/sublet/unsupported-allocators.c)
    else()
      target_sources(contexts-${mode} PRIVATE src/allocators/spatial/backing-allocator.c)
    endif()
  endforeach()
endif()
