add_subdirectory("${CAPSTONE_REPO_ROOT}/capstone/runtime" "${CMAKE_BINARY_DIR}/capstone-runtime")
add_library(replay-options INTERFACE)
target_link_libraries(replay-options INTERFACE Capstone::Runtime region-options)
target_include_directories(replay-options INTERFACE
  "${PROJECT_SOURCE_DIR}/src/shared" "${PROJECT_SOURCE_DIR}/src/allocators/sublet"
  "${PROJECT_SOURCE_DIR}/src/capstone-domain")
target_compile_options(replay-options INTERFACE
  "$<$<COMPILE_LANGUAGE:C>:-ffunction-sections;-fdata-sections>")
option(PG_MEMORY_PROFILE "Collect allocator memory snapshots in QEMU replay" OFF)
option(PG_SEPARATE_SCRATCH "Give both replay arms a separate identity-table region" ${PG_MEMORY_PROFILE})
if(PG_SEPARATE_SCRATCH)
  target_compile_definitions(replay-options INTERFACE PG_SEPARATE_SCRATCH)
endif()
if(PG_MEMORY_PROFILE)
  if(NOT PORT_PLATFORM STREQUAL "capstone-domain")
    message(FATAL_ERROR "Memory profiling is a QEMU domain configuration")
  endif()
  if(NOT PG_SEPARATE_SCRATCH)
    message(FATAL_ERROR "Memory profiles require separate replay scratch in both arms")
  endif()
  target_compile_definitions(replay-options INTERFACE PG_MEMORY_PROFILE)
  target_include_directories(replay-options INTERFACE "${PROJECT_SOURCE_DIR}/src/capstone-domain/memory")
endif()
option(PG_CHECK_DATA "Write/check payloads at free and realloc" ON)
if(PG_CHECK_DATA)
  target_compile_definitions(replay-options INTERFACE REPLAY_CHECK_DATA)
endif()

function(pg_manager name mode)
  if(mode STREQUAL "native")
    set(aset "${PG_SOURCE}/src/backend/utils/mmgr/aset.c")
  else()
    set(aset "${CMAKE_BINARY_DIR}/variants/${mode}/aset.c")
  endif()
  add_library(${name} OBJECT "${aset}" src/shared/postgres-compat.c)
  foreach(file mcxt generation slab bump alignedalloc memdebug)
    if(mode STREQUAL "sublet" AND file MATCHES "^(generation|slab|bump)$")
      target_sources(${name} PRIVATE "${CMAKE_BINARY_DIR}/variants/sublet/${file}.c")
    else()
      target_sources(${name} PRIVATE "${PG_SOURCE}/src/backend/utils/mmgr/${file}.c")
    endif()
  endforeach()
  target_link_libraries(${name} PUBLIC replay-options)
  if(NOT mode STREQUAL "native")
    target_include_directories(${name} PUBLIC "${CMAKE_BINARY_DIR}/variants/${mode}/include")
  endif()
  target_include_directories(${name} PUBLIC "${PG_SOURCE}/src/include" "${PG_SOURCE}/src/backend")
endfunction()

if(PORT_PLATFORM STREQUAL "native")
  pg_manager(manager-native native)
  add_executable(replay src/native/replay/main.c src/native/replay/printf.c src/shared/replay-engine.c)
  target_link_libraries(replay PRIVATE manager-native)
  target_link_options(replay PRIVATE LINKER:--gc-sections)
  add_executable(contexts-native tests/contexts-native.c src/native/replay/printf.c)
  target_link_libraries(contexts-native PRIVATE manager-native)
  target_link_options(contexts-native PRIVATE LINKER:--gc-sections)
  add_test(NAME contexts-native COMMAND contexts-native)
  set_tests_properties(contexts-native PROPERTIES LABELS native TIMEOUT 60)
else()
  enable_language(ASM)
  target_include_directories(replay-options SYSTEM INTERFACE "${PROJECT_SOURCE_DIR}/src/capstone-domain/include")
  pg_manager(manager-spatial spatial)
  pg_manager(manager-sublet sublet)
  set(domain_sources src/capstone-domain/domain-runtime.c src/capstone-domain/printf.c
    "${CAPSTONE_REPO_ROOT}/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c"
    "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/start.S"
    "${CAPSTONE_REPO_ROOT}/capstone/tests/runtime-qemu/gct-section-end.S"
    "${CAPSTONE_REPO_ROOT}/capstone/tests/runtime-qemu/domreq.S")
  set(link_script "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/link.ld")
  function(pg_domain name)
    add_executable(${name} ${ARGN} ${domain_sources})
    target_link_libraries(${name} PRIVATE replay-options)
    target_compile_definitions(${name} PRIVATE CAPSTONE_DOMREQ_DATA=${PG_DOMAIN_STACK_BYTES} CAPSTONE_DOMREQ_STACK=${PG_DOMAIN_STACK_BYTES})
    target_link_options(${name} PRIVATE --gc-sections -T "${link_script}")
    set_target_properties(${name} PROPERTIES SUFFIX .dom LINK_DEPENDS "${link_script}")
    add_custom_command(TARGET ${name} POST_BUILD
      COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/cmake/check-domain.py" "$<TARGET_FILE:${name}>")
  endfunction()
  pg_domain(replay-spatial src/allocators/spatial/replay.c src/allocators/spatial/backing-allocator.c
    src/capstone-domain/string.c src/shared/replay-engine.c)
  target_link_libraries(replay-spatial PRIVATE manager-spatial)
  pg_domain(replay-sublet src/allocators/sublet/replay.c src/allocators/sublet/context-pools.c src/allocators/sublet/unsupported-allocators.c
    src/capstone-domain/string.c src/shared/replay-engine.c)
  target_link_libraries(replay-sublet PRIVATE manager-sublet)
  if(PG_MEMORY_PROFILE)
    if(NOT PG_CHECK_DATA)
      message(FATAL_ERROR "Memory profiles require the replay's length and payload checks")
    endif()
    target_sources(replay-spatial PRIVATE src/capstone-domain/memory/profile.c)
    target_sources(replay-sublet PRIVATE src/capstone-domain/memory/profile.c)
  endif()
  pg_domain(context-hierarchy security-tests/capstone/context-hierarchy.c src/allocators/sublet/context-pools.c
    src/allocators/sublet/unsupported-allocators.c src/capstone-domain/string.c)
  target_link_libraries(context-hierarchy PRIVATE manager-sublet)
  target_compile_definitions(context-hierarchy PRIVATE "PG_DOM_FAIL_MARKER=\"__CAPSTONE_PG_HIER_FAILED__\\n\"")
  pg_domain(subpool-lifetimes security-tests/capstone/subpool-lifetimes.c src/allocators/sublet/context-pools.c)
  target_compile_definitions(subpool-lifetimes PRIVATE "PG_DOM_FAIL_MARKER=\"__CAPSTONE_PG_SUBPOOL_FAILED__\\n\"")
  foreach(mode spatial sublet)
    pg_domain(contexts-${mode} security-tests/capstone/contexts.c src/capstone-domain/string.c)
    target_include_directories(contexts-${mode} PRIVATE "${PROJECT_SOURCE_DIR}/tests")
    target_link_libraries(contexts-${mode} PRIVATE manager-${mode})
    if(mode STREQUAL "sublet")
      target_compile_definitions(contexts-${mode} PRIVATE PG_CONTEXTS_SUBLET)
      target_sources(contexts-${mode} PRIVATE src/allocators/sublet/context-pools.c
        src/allocators/sublet/unsupported-allocators.c)
    else()
      target_sources(contexts-${mode} PRIVATE src/allocators/spatial/backing-allocator.c)
    endif()
  endforeach()
endif()
