#ifndef CP16_H
#define CP16_H
/* CODE-LAYOUT sensitivity scan. Global COUNT was excluded: gc4..gc200 (8..208 carves) all
 * returned correctly. But an opaque clamp whose descriptor table was byte-identical to the
 * unclamped build still flipped SQLite's stage 11 -- a stage that never calls the modified
 * function. So the variable under test here is CODE LAYOUT, with the globals and the probe
 * held byte-identical across draws.
 *
 * 256 never-called functions shift .text by roughly 16 KiB. The probe is the same bounded
 * strlen over a pointer read out of a global struct.
 *   return = length * 1000 + (16 % 1000)
 */
struct cp16_kv { const char *z; long n; };
static const char *const cp16_lit[8] = {
  "alpha_one", "beta_two", "gamma_three", "delta_four",
  "epsilon_5", "zeta_six__", "eta_seven_", "theta_8___" };
static struct cp16_kv cp16_v = { cp16_lit[2], 0 };
__attribute__((noinline,used)) static long cp16_f0(long x){ long a=x+0; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f1(long x){ long a=x+1; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f2(long x){ long a=x+2; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f3(long x){ long a=x+3; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f4(long x){ long a=x+4; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f5(long x){ long a=x+5; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f6(long x){ long a=x+6; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f7(long x){ long a=x+7; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f8(long x){ long a=x+8; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f9(long x){ long a=x+9; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f10(long x){ long a=x+10; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f11(long x){ long a=x+11; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f12(long x){ long a=x+12; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f13(long x){ long a=x+13; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f14(long x){ long a=x+14; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f15(long x){ long a=x+15; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f16(long x){ long a=x+16; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f17(long x){ long a=x+17; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f18(long x){ long a=x+18; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f19(long x){ long a=x+19; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f20(long x){ long a=x+20; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f21(long x){ long a=x+21; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f22(long x){ long a=x+22; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f23(long x){ long a=x+23; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f24(long x){ long a=x+24; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f25(long x){ long a=x+25; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f26(long x){ long a=x+26; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f27(long x){ long a=x+27; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f28(long x){ long a=x+28; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f29(long x){ long a=x+29; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f30(long x){ long a=x+30; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f31(long x){ long a=x+31; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f32(long x){ long a=x+32; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f33(long x){ long a=x+33; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f34(long x){ long a=x+34; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f35(long x){ long a=x+35; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f36(long x){ long a=x+36; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f37(long x){ long a=x+37; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f38(long x){ long a=x+38; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f39(long x){ long a=x+39; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f40(long x){ long a=x+40; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f41(long x){ long a=x+41; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f42(long x){ long a=x+42; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f43(long x){ long a=x+43; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f44(long x){ long a=x+44; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f45(long x){ long a=x+45; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f46(long x){ long a=x+46; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f47(long x){ long a=x+47; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f48(long x){ long a=x+48; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f49(long x){ long a=x+49; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f50(long x){ long a=x+50; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f51(long x){ long a=x+51; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f52(long x){ long a=x+52; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f53(long x){ long a=x+53; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f54(long x){ long a=x+54; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f55(long x){ long a=x+55; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f56(long x){ long a=x+56; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f57(long x){ long a=x+57; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f58(long x){ long a=x+58; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f59(long x){ long a=x+59; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f60(long x){ long a=x+60; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f61(long x){ long a=x+61; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f62(long x){ long a=x+62; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f63(long x){ long a=x+63; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f64(long x){ long a=x+64; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f65(long x){ long a=x+65; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f66(long x){ long a=x+66; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f67(long x){ long a=x+67; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f68(long x){ long a=x+68; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f69(long x){ long a=x+69; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f70(long x){ long a=x+70; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f71(long x){ long a=x+71; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f72(long x){ long a=x+72; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f73(long x){ long a=x+73; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f74(long x){ long a=x+74; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f75(long x){ long a=x+75; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f76(long x){ long a=x+76; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f77(long x){ long a=x+77; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f78(long x){ long a=x+78; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f79(long x){ long a=x+79; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f80(long x){ long a=x+80; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f81(long x){ long a=x+81; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f82(long x){ long a=x+82; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f83(long x){ long a=x+83; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f84(long x){ long a=x+84; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f85(long x){ long a=x+85; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f86(long x){ long a=x+86; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f87(long x){ long a=x+87; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f88(long x){ long a=x+88; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f89(long x){ long a=x+89; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f90(long x){ long a=x+90; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f91(long x){ long a=x+91; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f92(long x){ long a=x+92; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f93(long x){ long a=x+93; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f94(long x){ long a=x+94; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f95(long x){ long a=x+95; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f96(long x){ long a=x+96; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f97(long x){ long a=x+97; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f98(long x){ long a=x+98; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f99(long x){ long a=x+99; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f100(long x){ long a=x+100; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f101(long x){ long a=x+101; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f102(long x){ long a=x+102; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f103(long x){ long a=x+103; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f104(long x){ long a=x+104; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f105(long x){ long a=x+105; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f106(long x){ long a=x+106; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f107(long x){ long a=x+107; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f108(long x){ long a=x+108; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f109(long x){ long a=x+109; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f110(long x){ long a=x+110; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f111(long x){ long a=x+111; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f112(long x){ long a=x+112; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f113(long x){ long a=x+113; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f114(long x){ long a=x+114; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f115(long x){ long a=x+115; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f116(long x){ long a=x+116; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f117(long x){ long a=x+117; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f118(long x){ long a=x+118; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f119(long x){ long a=x+119; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f120(long x){ long a=x+120; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f121(long x){ long a=x+121; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f122(long x){ long a=x+122; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f123(long x){ long a=x+123; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f124(long x){ long a=x+124; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f125(long x){ long a=x+125; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f126(long x){ long a=x+126; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f127(long x){ long a=x+127; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f128(long x){ long a=x+128; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f129(long x){ long a=x+129; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f130(long x){ long a=x+130; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f131(long x){ long a=x+131; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f132(long x){ long a=x+132; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f133(long x){ long a=x+133; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f134(long x){ long a=x+134; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f135(long x){ long a=x+135; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f136(long x){ long a=x+136; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f137(long x){ long a=x+137; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f138(long x){ long a=x+138; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f139(long x){ long a=x+139; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f140(long x){ long a=x+140; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f141(long x){ long a=x+141; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f142(long x){ long a=x+142; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f143(long x){ long a=x+143; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f144(long x){ long a=x+144; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f145(long x){ long a=x+145; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f146(long x){ long a=x+146; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f147(long x){ long a=x+147; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f148(long x){ long a=x+148; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f149(long x){ long a=x+149; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f150(long x){ long a=x+150; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f151(long x){ long a=x+151; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f152(long x){ long a=x+152; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f153(long x){ long a=x+153; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f154(long x){ long a=x+154; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f155(long x){ long a=x+155; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f156(long x){ long a=x+156; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f157(long x){ long a=x+157; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f158(long x){ long a=x+158; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f159(long x){ long a=x+159; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f160(long x){ long a=x+160; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f161(long x){ long a=x+161; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f162(long x){ long a=x+162; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f163(long x){ long a=x+163; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f164(long x){ long a=x+164; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f165(long x){ long a=x+165; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f166(long x){ long a=x+166; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f167(long x){ long a=x+167; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f168(long x){ long a=x+168; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f169(long x){ long a=x+169; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f170(long x){ long a=x+170; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f171(long x){ long a=x+171; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f172(long x){ long a=x+172; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f173(long x){ long a=x+173; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f174(long x){ long a=x+174; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f175(long x){ long a=x+175; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f176(long x){ long a=x+176; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f177(long x){ long a=x+177; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f178(long x){ long a=x+178; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f179(long x){ long a=x+179; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f180(long x){ long a=x+180; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f181(long x){ long a=x+181; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f182(long x){ long a=x+182; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f183(long x){ long a=x+183; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f184(long x){ long a=x+184; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f185(long x){ long a=x+185; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f186(long x){ long a=x+186; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f187(long x){ long a=x+187; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f188(long x){ long a=x+188; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f189(long x){ long a=x+189; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f190(long x){ long a=x+190; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f191(long x){ long a=x+191; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f192(long x){ long a=x+192; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f193(long x){ long a=x+193; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f194(long x){ long a=x+194; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f195(long x){ long a=x+195; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f196(long x){ long a=x+196; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f197(long x){ long a=x+197; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f198(long x){ long a=x+198; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f199(long x){ long a=x+199; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f200(long x){ long a=x+200; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f201(long x){ long a=x+201; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f202(long x){ long a=x+202; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f203(long x){ long a=x+203; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f204(long x){ long a=x+204; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f205(long x){ long a=x+205; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f206(long x){ long a=x+206; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f207(long x){ long a=x+207; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f208(long x){ long a=x+208; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f209(long x){ long a=x+209; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f210(long x){ long a=x+210; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f211(long x){ long a=x+211; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f212(long x){ long a=x+212; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f213(long x){ long a=x+213; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f214(long x){ long a=x+214; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f215(long x){ long a=x+215; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f216(long x){ long a=x+216; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f217(long x){ long a=x+217; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f218(long x){ long a=x+218; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f219(long x){ long a=x+219; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f220(long x){ long a=x+220; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f221(long x){ long a=x+221; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f222(long x){ long a=x+222; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f223(long x){ long a=x+223; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f224(long x){ long a=x+224; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f225(long x){ long a=x+225; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f226(long x){ long a=x+226; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f227(long x){ long a=x+227; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f228(long x){ long a=x+228; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f229(long x){ long a=x+229; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f230(long x){ long a=x+230; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f231(long x){ long a=x+231; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f232(long x){ long a=x+232; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f233(long x){ long a=x+233; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f234(long x){ long a=x+234; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f235(long x){ long a=x+235; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f236(long x){ long a=x+236; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f237(long x){ long a=x+237; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f238(long x){ long a=x+238; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f239(long x){ long a=x+239; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f240(long x){ long a=x+240; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f241(long x){ long a=x+241; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f242(long x){ long a=x+242; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f243(long x){ long a=x+243; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f244(long x){ long a=x+244; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f245(long x){ long a=x+245; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f246(long x){ long a=x+246; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f247(long x){ long a=x+247; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f248(long x){ long a=x+248; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f249(long x){ long a=x+249; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f250(long x){ long a=x+250; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f251(long x){ long a=x+251; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f252(long x){ long a=x+252; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f253(long x){ long a=x+253; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f254(long x){ long a=x+254; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
__attribute__((noinline,used)) static long cp16_f255(long x){ long a=x+255; a^=a<<3; a+=a>>2; a*=3; a^=a<<5; a+=a>>1; a*=7; a^=a<<2; return a; }
static unsigned cp16_compute(void)
{
  int k = 0;
  const char *z;
  cp16_v.n = 1;
  z = cp16_v.z;
  while (k < 64 && z[k]) k++;
  return (unsigned)(k * 1000 + (16 % 1000));
}
#endif
