#!/usr/bin/env python3
"""Cap-table builder-glue generator (silicon ladder, Stage 0a).

Reads the `-capstone-gp-captable` descriptor `.capstone_gp_table` from a compiled
domain object and emits the app-specific `BUILD_GP_CAPTABLE` assembler macro that
the generic entry glue (`start-gp-captable-generic.S`) #includes. This replaces the
hand-baked N=1 macro in `start-gpfree-captable-app.S` with one derived automatically
from the compiler's descriptor, for arbitrary global counts.

Descriptor layout (CapstoneAsmPrinter.cpp:849), in getGpCaptableIndex order so slot
i in the runtime table matches `ldc gp[i]` in the code:
    u64 count
    per global: { u64 size, u64 align, i64 init_off }
`init_off == 0` -> zero-init (.bss). `init_off != 0` -> the global has an image
initializer template that must be COPIED into the carved data storage; that copy
reads the code image (the "initialized global on silicon" question) and is NOT yet
handled here -- we error out so nothing silently miscomputes.

Silicon rule baked in: storage is carved from `sp` (the DATA-authority cscratch
region) via `split`, never from the code image, and sizes are baked as immediates
(no runtime descriptor read from the image).
"""
import os
import struct
import subprocess
import sys


def die(msg):
    sys.stderr.write("gen-gp-captable-glue: " + msg + "\n")
    sys.exit(1)


def align_up(n, a):
    return (n + a - 1) // a * a


def main():
    if len(sys.argv) != 3:
        die("usage: gen-gp-captable-glue.py <domain_main.o> <out.inc>")
    main_o, out_inc = sys.argv[1], sys.argv[2]
    llvm_bin = os.environ.get("CAPSTONE_LLVM_BIN", "")
    objcopy = os.path.join(llvm_bin, "llvm-objcopy") if llvm_bin else "llvm-objcopy"
    readelf = os.path.join(llvm_bin, "llvm-readelf") if llvm_bin else "llvm-readelf"

    # Dump the descriptor section (absent => 0 indexable globals => empty macro).
    binp = out_inc + ".gptbl.bin"
    r = subprocess.run([objcopy, "--dump-section", ".capstone_gp_table=" + binp, main_o],
                       capture_output=True)
    if r.returncode != 0 or not os.path.exists(binp):
        with open(out_inc, "w") as f:
            f.write("/* generated: no .capstone_gp_table (0 indexable globals) */\n"
                    ".macro BUILD_GP_CAPTABLE\n.endm\n")
        print("gen: 0 globals (no descriptor) -> empty BUILD_GP_CAPTABLE")
        return

    data = open(binp, "rb").read()
    if len(data) < 8:
        die("descriptor too short")
    (count,) = struct.unpack_from("<Q", data, 0)
    recs = []
    off = 8
    for i in range(count):
        if off + 24 > len(data):
            die("descriptor truncated at record %d" % i)
        size, align, init_off = struct.unpack_from("<QQq", data, off)
        off += 24
        recs.append((size, align, init_off))

    # Initialized globals appear as relocations against the section (init_off is a
    # link-time sym-. diff). Detect and refuse for this .bss-only rung.
    rr = subprocess.run([readelf, "-r", main_o], capture_output=True, text=True)
    if ".capstone_gp_table" in (rr.stdout or ""):
        die("this domain has INITIALIZED globals (relocations in .capstone_gp_table).\n"
            "  The template copy reads the code image -- the open silicon question.\n"
            "  Rung 1 supports zero-init (.bss) globals only. Make globals .bss and\n"
            "  initialize in code, or extend the generator with the template copy.")

    table_bytes = count * 16
    if table_bytes > 2047:
        die("cap-table (%d B) exceeds a 12-bit immediate; needs li+sub (TODO)" % table_bytes)

    lines = []
    lines.append("/* GENERATED by gen-gp-captable-glue.py -- do not edit. */")
    lines.append("/* %d global(s); cap-table = %d bytes. */" % (count, table_bytes))
    lines.append(".macro BUILD_GP_CAPTABLE")
    lines.append("  lcc(t1, sp, 4)                 /* t1 = sp.END */")
    lines.append("  addi t1, t1, -%d               /* reserve N*16 cap-table */" % table_bytes)
    lines.append("  split(gp, sp, t1)              /* gp = [t1,END) table; sp = [base,t1) */")
    lines.append("  delin(gp)")
    for i, (size, align, init_off) in enumerate(recs):
        stor = align_up(size, 16)  # 16-align keeps split bounds + storage base aligned
        if stor > 2040:
            die("global %d storage %d B > unrolled-zero limit; needs a zero loop (TODO)" % (i, stor))
        lines.append("  /* global %d: size=%d align=%d -> %d B (.bss, zero) */"
                     % (i, size, align, stor))
        lines.append("  addi t1, t1, -%d" % stor)
        lines.append("  split(t2, sp, t1)             /* t2 = storage cap */")
        lines.append("  delin(t2)")
        for k in range(0, stor, 8):
            lines.append("  sd x0, %d(t2)" % k)
        lines.append("  stc(t2, gp, %d)               /* cap-table[%d] */" % (i * 16, i))
    lines.append("  scc(sp, sp, t1)               /* sp.cursor = top of remaining stack */")
    lines.append("  delin(sp)")
    lines.append(".endm")
    with open(out_inc, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("gen: %d global(s), table=%d B -> %s" % (count, table_bytes, out_inc))


if __name__ == "__main__":
    main()
