# What both domain builds do, sourced by each of them.
#
# build-mmgr-domain.sh builds the manager without the discipline and
# build-mmgr-sublet.sh builds it with, from the same configured tree. They
# differ in one patch on aset.c, one patch on the chunk header, the level below
# they link, and the driver. Everything else was the same file twice, and the
# two copies had already drifted: only one of them checked the image against
# the size the module can create.
#
# Functions here read and write these globals, which is deliberate: bash cannot
# return an array, and FLAGS and OBJS are arrays that each script builds up
# differently.
#
#   HERE REPO_ROOT        set by the caller before sourcing
#   CLANG LD_LLD READOBJ  set by pgdom_tools
#   FLAGS[]               set by the caller, read by pgdom_manager
#   OBJS[]                appended to by pgdom_manager
#
# Nothing here is specific to PostgreSQL except the seven file names, and those
# are the caller's FILES.

# The toolchain, and a refusal that names what is missing rather than failing
# at the first compile.
pgdom_tools() {
  LLVM=${CAPSTONE_LLVM_BUILD_DIR:-$REPO_ROOT/llvm/build-rel}
  CLANG=${CLANG:-$LLVM/bin/clang}
  LD_LLD=${LD_LLD:-$LLVM/bin/ld.lld}
  READOBJ=${READOBJ:-$LLVM/bin/llvm-readobj}
  local t
  for t in "$CLANG" "$LD_LLD"; do
    [ -x "$t" ] || { echo "no $t; set CAPSTONE_LLVM_BUILD_DIR" >&2; return 1; }
  done
  [ -f "$SRC/src/include/pg_config.h" ] || {
    echo "no configured PostgreSQL tree at $SRC; run build-mmgr-host.sh first" >&2
    return 1; }
}

# The two headers configure got wrong for this target, shadowed rather than
# patched in the tree, so the host arm keeps the tree it was configured for.
# Extra memorychunk patches are applied in the order given, on top.
pgdom_headers() {
  local dom_out=$1; shift
  mkdir -p "$dom_out/obj" "$dom_out/include/utils"
  cp "$SRC/src/include/utils/memutils_memorychunk.h" "$dom_out/include/utils/"
  local p
  for p in "$@"; do
    patch -s -F0 -p0 "$dom_out/include/utils/memutils_memorychunk.h" < "$p"
  done
  # pg_config.h is generated by configure and differs between machines, so one
  # line is rewritten and the rewrite is checked, rather than a patch that
  # would go stale on the next host.
  sed 's/^#define MAXIMUM_ALIGNOF 8$/#define MAXIMUM_ALIGNOF 16/' \
      "$SRC/src/include/pg_config.h" > "$dom_out/include/pg_config.h"
  grep -qx '#define MAXIMUM_ALIGNOF 16' "$dom_out/include/pg_config.h" || {
    echo "MAXIMUM_ALIGNOF was not 8 in $SRC/src/include/pg_config.h; read it and decide" >&2
    return 2; }
}

# The seven files of the manager, for capstone64. aset.c is patched into
# $dom_out first, because it carries what a sixteen-byte pointer forces and,
# for the protected arm, the discipline as well.
pgdom_manager() {
  local dom_out=$1; shift
  local f src p
  for f in $FILES; do
    src=$SRC/src/backend/utils/mmgr/$f
    if [ "$f" = aset.c ]; then
      cp "$src" "$dom_out/aset.c"
      for p in "$@"; do
        patch -s -F0 -p0 "$dom_out/aset.c" < "$p"
      done
      src=$dom_out/aset.c
    fi
    "$CLANG" "${FLAGS[@]}" -c "$src" -o "$dom_out/obj/${f%.c}.o"
    OBJS+=("$dom_out/obj/${f%.c}.o")
  done

  # The repository's freestanding string set, not this port's, because its
  # copies preserve capability tags. A second implementation of memcpy cost a
  # run: a byte loop copies a pointer's address bits and drops its out-of-band
  # tag, so the copy comes back untagged and the next store faults
  # (aset.c:1246, cause 24, a block's prev pointer).
  "$CLANG" "${FLAGS[@]}" -c \
      "$REPO_ROOT/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c" \
      -o "$dom_out/obj/beebs_string.o"
  OBJS+=("$dom_out/obj/beebs_string.o")
}

# The entry, the declared requirement, the link, and the two checks that have
# each cost a run.
pgdom_link() {
  local dom_out=$1 out_dom=$2
  local start=$REPO_ROOT/capstone/my_first_domain/start.S
  local script=$REPO_ROOT/capstone/my_first_domain/link.ld
  local domreq=$REPO_ROOT/capstone/tests/runtime-qemu/domreq.S

  echo "== the domain's entry and its declared requirement"
  "$CLANG" -target capstone64-unknown-elf -Xclang -target-feature -Xclang +m \
      -ffreestanding -O0 -c "$start" -o "$dom_out/obj/start.o"
  "$CLANG" -target capstone64-unknown-elf -ffreestanding \
      -DCAPSTONE_DOMREQ_DATA=$PG_DOMAIN_DATA \
      -DCAPSTONE_DOMREQ_STACK=$PG_DOMAIN_STACK \
      -c "$domreq" -o "$dom_out/obj/domreq.o"

  _segs() { "$READOBJ" --program-headers "$out_dom" | grep -E 'Offset|VirtualAddress|FileSize|MemSize'; }

  echo "== linking"
  "$LD_LLD" --gc-sections -T "$script" -o "$out_dom" \
      "$dom_out/obj/start.o" "${OBJS[@]}"
  local before
  before=$(_segs)
  "$LD_LLD" --gc-sections -T "$script" -o "$out_dom" \
      "$dom_out/obj/start.o" "${OBJS[@]}" "$dom_out/obj/domreq.o"
  # The declaration is non-alloc, so nothing loaded may move. Verified and not
  # asserted: four added instructions have flipped a passing run on this
  # project.
  if [[ "$(_segs)" != "$before" ]]; then
    echo "domreq.S moved a loaded byte; the declaration must be non-alloc" >&2
    return 2
  fi

  # The image has a ceiling and it is not obvious from the failure. The module
  # asks the buddy allocator for the image doubled, rounded up to a
  # power-of-two page count, and that allocator stops at order ten, four
  # megabytes. An image above two megabytes cannot be created at all, and the
  # guest says only "create_dom failed". The static tables in
  # port/pg_subpool.h are the usual reason and can be overridden.
  local mem
  mem=$("$READOBJ" --program-headers "$out_dom" | awk '/MemSize/ { print $2; exit }')
  if [ "${mem:-0}" -gt $((2 * 1024 * 1024)) ]; then
    echo "the domain image is $mem bytes, above the two megabytes the module can create" >&2
    return 2
  fi
  echo "image $mem bytes of the two megabytes the module can create"
}
