#!/usr/bin/env bash
# Build reference mruby as a pure-capability domain, running precompiled bytecode.
#
# Needs an mruby tree that has ALREADY been built for the host, because two of
# its inputs are generated by mruby's own build system and are target
# independent: build/host/mrblib/mrblib.c (the Ruby-level standard library, as
# bytecode) and build/host/include/mruby/presym/ (the symbol tables). Produce
# them with `rake` in the mruby tree; this script does not reimplement that.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/../../tests/capstone-test-env.sh"

REPO_ROOT=$CAPSTONE_REPO_ROOT
CLANG=${CAPSTONE_CLANG:?}
LD_LLD=${CAPSTONE_LD_LLD:?}
OUT_DIR=${OUT_DIR:-$CAPSTONE_TMP_ROOT/musl-capstone-mruby}
OBJ_DIR="$OUT_DIR/obj"
OUT_DOM=${OUT_DOM:-$OUT_DIR/mruby_probe.dom}
OUT_HOST=${OUT_HOST:-$OUT_DIR/mruby_probe.user}

RUNTIME_DIR="$SCRIPT_DIR/../runtime"
LINKER_SCRIPT="$REPO_ROOT/capstone/my_first_domain/link.ld"
GUEST_CC=${GUEST_CC:-$CAPSTONE_BUILDROOT_DIR/build/host/bin/riscv64-buildroot-linux-gnu-gcc}
LIBCAPSTONE_C="$REPO_ROOT/capstone/caplifive-buildroot/package/modcapstone/userspace/lib/libcapstone.c"
SETJMP_SRC="$REPO_ROOT/xlang/lua-cdp/capstone-lua/capstone_setjmp.S"

ARCHIVE=${ARCHIVE:-$CAPSTONE_TMP_ROOT/musl-capstone-build/libc-capstone.a}
MUSL_SRC_DIR=${MUSL_SRC_DIR:-$CAPSTONE_TMP_ROOT/musl-src/musl-1.2.5}
MRUBY_SRC=${MRUBY_SRC:-$HOME/cheri/mruby-purecap}

for needed in "$ARCHIVE" "$MUSL_SRC_DIR/arch/capstone64/syscall_arch.h" "$SETJMP_SRC" \
              "$MRUBY_SRC/src/vm.c" "$MRUBY_SRC/build/host/mrblib/mrblib.c" \
              "$MRUBY_SRC/build/host/include/mruby/presym/id.h" \
              "$MRUBY_SRC/build/host/bin/mrbc"; do
  [[ -e "$needed" ]] || { echo "missing prerequisite: $needed" >&2; exit 2; }
done

# THE FOUR CONFIG MACROS, all upstream-supported, each forced by this machine:
#
#   MRB_NO_BOXING           boxing_word.h packs an mrb_value into one 64-bit
#                           word by tagging the pointer; its static assert fails
#                           outright with 16-byte pointers. This one is ours --
#                           the CHERI port did not need it.
#   MRB_NO_DIRECT_THREADING the VM's computed-goto dispatch is a second,
#                           independent absolute-addressed jump table, the same
#                           mechanism Lua needed LUA_USE_JUMPTABLE=0 for.
#   POOL_ALIGNMENT=16       the parser pool hands out 8-aligned cells whose
#                           node* fields are 16-byte capabilities.
#   MRB_USE_METHOD_T_STRUCT the method table otherwise stores a tagged pointer.
#
# The last two come from the CHERI port (xlang/cheri/mruby-port/README.md) and
# are about pointer WIDTH, which is why they carry over; its TLS flags do not,
# because a domain has no dynamic linker.
#
# MRB_NO_STDIO: not because stdio is missing -- printf works now -- but because
# this first probe is the VM alone. Adding mruby-print is the next step.
MRUBY_FLAGS=(
  -target capstone64-unknown-elf
  -Xclang -target-feature -Xclang +m
  -Xclang -target-feature -Xclang +a
  -nostdinc -ffreestanding -fno-builtin
  -fno-optimize-sibling-calls -fno-jump-tables
  -D_XOPEN_SOURCE=700
  -DMRB_NO_BOXING -DMRB_NO_DIRECT_THREADING -DMRB_NO_STDIO
  -DPOOL_ALIGNMENT=16 -DMRB_USE_METHOD_T_STRUCT
  # MRUBY_PROBE_STACK_DOUBLING=1 adds -DMRB_STACK_EXTEND_DOUBLING, an upstream
  # mruby option. It is DIAGNOSTIC and must not be on for a published number:
  # mruby's default is LINEAR stack growth, chosen because it "saves memory on
  # small devices" -- true of the live set, and exactly wrong for an allocator
  # that never reclaims, where the cumulative carve is the sum of every stack
  # size ever allocated and linear growth makes that sum quadratic. Turning it
  # on separates "the arena is too small for this workload" from "the workload
  # stops for some other reason".
  ${MRUBY_PROBE_STACK_DOUBLING:+-DMRB_STACK_EXTEND_DOUBLING}
  # musl's <math.h> classify macros end in a long-double arm that -O0 does not
  # fold away, so numeric.c and fmt_fp.c pull __signbitl, __fpclassifyl and
  # __extenddftf2, none of which exist (C-20). A -D on this command line does
  # NOT work -- math.h redefines the same names later. The header explains why
  # a forced include does.
  -include "$SCRIPT_DIR/../libc-ext/capstone-math-double.h"
  -I"$MRUBY_SRC/include" -I"$MRUBY_SRC/build/host/include"
  -I"$MUSL_SRC_DIR/arch/capstone64" -I"$MUSL_SRC_DIR/arch/generic"
  -I"$MUSL_SRC_DIR/obj/include" -I"$MUSL_SRC_DIR/include"
  -ffunction-sections -fdata-sections
  -O0 -w -Wno-int-conversion -Wno-error=int-conversion
)

rm -rf "$OBJ_DIR"; mkdir -p "$OBJ_DIR"
OBJS=()

# The Ruby chunk, compiled to bytecode BY THE HOST mrbc and emitted as a C
# array. This is the step that keeps the parser out of the domain.
"$MRUBY_SRC/build/host/bin/mrbc" -B probe_irep -o "$OBJ_DIR/probe_irep.c" \
                                 "$SCRIPT_DIR/probe.rb"

# STAGE 7 needs a LADDER of ireps rather than one: the fault is inside
# mrb_top_run, and an interpreter loop does not decompose by call structure. It
# decomposes by BYTECODE, so each rung is a slightly larger Ruby chunk and the
# last rung that returns names the construct. All six go into ONE image.
if [[ ${MRUBY_PROBE_STAGE:-0} -ge 7 ]]; then
  : > "$OBJ_DIR/ladder_ireps.c"
  for rb in "$SCRIPT_DIR"/ladder/*.rb; do
    sym="ladder_$(basename "$rb" .rb)"
    "$MRUBY_SRC/build/host/bin/mrbc" -B "$sym" -o "$OBJ_DIR/$sym.c" "$rb"
    cat "$OBJ_DIR/$sym.c" >> "$OBJ_DIR/ladder_ireps.c"
  done
fi

"$CLANG" -target capstone64-unknown-elf -Xclang -target-feature -Xclang +m \
  -ffreestanding -O0 -c "$RUNTIME_DIR/start-musl.S" -o "$OBJ_DIR/start-musl.o"
OBJS+=("$OBJ_DIR/start-musl.o")

"$CLANG" -target capstone64-unknown-elf -Xclang -target-feature -Xclang +m \
  -ffreestanding -O0 -c "$SETJMP_SRC" -o "$OBJ_DIR/setjmp.o"
OBJS+=("$OBJ_DIR/setjmp.o")

# MRUBY_PROBE_REVOKE=1 swaps the libc allocator for the REVOKING one: every
# allocation is an independently revocable SPLIT off a host-granted linear
# arena, and free() revokes it. That is the configuration a security number may
# be measured on; libc-ext/malloc.c is not, and says so itself.
#
# revoke_arena_domain.c defines malloc/free/realloc, and our objects precede the
# archive on the link line, so libc-ext/malloc.c is simply never pulled. The
# host program needs the same macro: it has to create and transfer a third
# region, and share order is capture order.
ARENA_FLAGS=()
HOST_FLAGS=()
if [[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]]; then
  ARENA_FLAGS=(-DCAPSTONE_DOMAIN_ARENA)
  HOST_FLAGS=(-DCAPSTONE_DOMAIN_ARENA)
fi

# MRUBY_PROBE_ARENA_MB makes the arena size a VARIABLE rather than a constant to
# be edited by hand. It is the thing most likely to be the reason a workload
# stops early, because the revoking allocator never coalesces: the arena has to
# hold the whole CUMULATIVE carve, not the live set. Only meaningful with
# MRUBY_PROBE_REVOKE=1; the host and the domain must agree, and they do because
# both read this one variable.
if [[ -n ${MRUBY_PROBE_ARENA_MB:-} ]]; then
  HOST_FLAGS+=(-DHC_HOST_ARENA_SIZE="(${MRUBY_PROBE_ARENA_MB}UL * 1024 * 1024)")
fi

"$CLANG" "${MRUBY_FLAGS[@]}" "${ARENA_FLAGS[@]}" -c "$RUNTIME_DIR/hostcall.c" \
         -o "$OBJ_DIR/hostcall.o"
OBJS+=("$OBJ_DIR/hostcall.o")

if [[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]]; then
  "$CLANG" "${MRUBY_FLAGS[@]}" "${ARENA_FLAGS[@]}" \
    -I"$REPO_ROOT/capstone/benchmarks/sqlite" \
    -c "$REPO_ROOT/xlang/common/revoke_arena_domain.c" -o "$OBJ_DIR/revoke_arena.o"
  OBJS+=("$OBJ_DIR/revoke_arena.o")
fi

# -U__GNUC__ for hash.c ONLY: ib_capa_to_bit calls __builtin_ctz, which crashes
# the backend (ISSUES.md C-24). Undefining __GNUC__ selects mruby's own de
# Bruijn fallback, written for compilers without the builtin. Per file, because
# y.tab.c needs __GNUC__ for alloca -- not that this build compiles y.tab.c.
for src in "$MRUBY_SRC"/src/*.c "$MRUBY_SRC/build/host/mrblib/mrblib.c"; do
  base=$(basename "$src" .c)
  extra=()
  [[ $base == hash ]] && extra=(-U__GNUC__)
  "$CLANG" "${MRUBY_FLAGS[@]}" "${extra[@]}" -c "$src" -o "$OBJ_DIR/mrb_$base.o"
  OBJS+=("$OBJ_DIR/mrb_$base.o")
done

# MRUBY_WITH_PARSER=1 adds the compiler gem, so the domain evaluates Ruby SOURCE
# instead of only precompiled bytecode. Off by default, and the order matters:
# the bytecode variant is the smaller image and it separates "does the VM run"
# from "does the parser run". Answering both in one image would leave a failure
# ambiguous between them.
PROBE_EXTRA=()
[[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_REVOKE)
# MRUBY_PROBE_CDP=1 runs the corpus's largest mechanism class on the real
# interpreter; MRUBY_PROBE_CDP_CONTROL=1 is its matched arm with revocation off.
[[ ${MRUBY_PROBE_CDP:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_CDP)
[[ ${MRUBY_PROBE_CDP_CONTROL:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_CDP_CONTROL)
# MRUBY_PROBE_ROW=<n> runs xlang corpus row <n>'s OWN trigger.rb, embedded
# verbatim. Only rows whose pinned mruby version matches MRUBY_SRC are
# meaningful; row 10's pinned commit is the tree this port was validated on.
# MRUBY_PROBE_GEMS="eval hash-ext" links those mrbgems and generates the
# mrb_init_mrbgems the probe otherwise stubs out. Corpus triggers need them:
# row 9's first line is `eval(...)`, which is not core mruby at all, and without
# the gem the trigger raises NoMethodError before reaching its offending access
# -- a run where both arms report identically and neither means anything.
#
# Gems with an mrblib half need mrbc and a generated loader; that is NOT built
# here, so such a gem is refused loudly rather than half-linked.
if [[ -n ${MRUBY_PROBE_GEMS:-} ]]; then
  GEM_INIT="$OBJ_DIR/gem_init.c"
  {
    echo '/* GENERATED by build-mruby-probe.sh -- do not edit. */'
    echo '#include <mruby.h>'
  } > "$GEM_INIT"
  for gem in $MRUBY_PROBE_GEMS; do
    GEM_DIR="$MRUBY_SRC/mrbgems/mruby-$gem"
    [[ -d "$GEM_DIR/src" ]] || { echo "no such gem: mruby-$gem" >&2; exit 2; }
    if compgen -G "$GEM_DIR/mrblib/*.rb" > /dev/null; then
      echo "mruby-$gem has an mrblib half, which this build cannot generate" >&2
      exit 2
    fi
    sym="mrb_mruby_${gem//-/_}_gem_init"
    for gsrc in "$GEM_DIR"/src/*.c; do
      gbase=$(basename "$gsrc" .c)
      "$CLANG" "${MRUBY_FLAGS[@]}" -I"$MRUBY_SRC/mrbgems/mruby-compiler/core" \
               -c "$gsrc" -o "$OBJ_DIR/gem_${gem//-/_}_$gbase.o"
      OBJS+=("$OBJ_DIR/gem_${gem//-/_}_$gbase.o")
    done
    echo "void $sym(mrb_state *mrb);" >> "$GEM_INIT"
  done
  {
    echo 'void mrb_init_mrbgems(mrb_state *mrb) {'
    for gem in $MRUBY_PROBE_GEMS; do
      echo "  mrb_mruby_${gem//-/_}_gem_init(mrb);"
    done
    echo '}'
    echo 'void mrb_final_mrbgems(mrb_state *mrb) { (void)mrb; }'
  } >> "$GEM_INIT"
  "$CLANG" "${MRUBY_FLAGS[@]}" -c "$GEM_INIT" -o "$OBJ_DIR/gem_init.o"
  OBJS+=("$OBJ_DIR/gem_init.o")
  PROBE_EXTRA+=(-DMRUBY_PROBE_GEMS)
fi

if [[ -n ${MRUBY_PROBE_ROW:-} ]]; then
  ROW_RB="$REPO_ROOT/xlang/repro/${MRUBY_PROBE_ROW}/trigger.rb"
  python3 "$SCRIPT_DIR/embed-ruby.py" "$ROW_RB" "$OBJ_DIR/row_trigger.c" row_trigger
  PROBE_EXTRA+=(-DMRUBY_PROBE_ROW="${MRUBY_PROBE_ROW}")
fi
# MRUBY_PROBE_BUMP=1 swaps the probe's allocator for an O(1) bump arena. See the
# comment in mruby_probe.c: it is the matched arm for a wedge, differing from the
# libc allocator in exactly one property.
[[ ${MRUBY_PROBE_BUMP:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_BUMP)
# MRUBY_PROBE_STAGE=N builds one arm of the staged batch: 1 allocates the state,
# 2 adds mrb_gc_init, 3 adds mrb_init_core, 0 (default) is the full run. Each arm
# RETURNS a marker instead of running to the failure, so a wedge costs only the
# arms after it. See run-mruby-stages.sh.
[[ ${MRUBY_PROBE_STAGE:-0} != 0 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_STAGE="${MRUBY_PROBE_STAGE}")
if [[ ${MRUBY_WITH_PARSER:-0} == 1 ]]; then
  PARSER_CORE="$MRUBY_SRC/mrbgems/mruby-compiler/core"
  python3 "$SCRIPT_DIR/patch-parser.py" "$PARSER_CORE/y.tab.c" \
          "$OBJ_DIR/y.tab.fixed.c"
  "$CLANG" "${MRUBY_FLAGS[@]}" -I"$PARSER_CORE" -c "$OBJ_DIR/y.tab.fixed.c" \
           -o "$OBJ_DIR/mrb_parser.o"
  "$CLANG" "${MRUBY_FLAGS[@]}" -I"$PARSER_CORE" -c "$PARSER_CORE/codegen.c" \
           -o "$OBJ_DIR/mrb_codegen.o"
  OBJS+=("$OBJ_DIR/mrb_parser.o" "$OBJ_DIR/mrb_codegen.o")
  PROBE_EXTRA+=(-DMRUBY_PROBE_PARSER)   # += : the bump flag must survive
fi

"$CLANG" "${MRUBY_FLAGS[@]}" "${PROBE_EXTRA[@]}" -I"$OBJ_DIR" \
         -c "$SCRIPT_DIR/mruby_probe.c" -o "$OBJ_DIR/mruby_probe.o"
OBJS+=("$OBJ_DIR/mruby_probe.o")

"$LD_LLD" --gc-sections -T "$LINKER_SCRIPT" -o "$OUT_DOM" "${OBJS[@]}" "$ARCHIVE"

image=$("$CAPSTONE_LLVM_READOBJ" --program-headers "$OUT_DOM" \
         | awk '/MemSize/ {print $2; exit}')
tot=4096; while (( tot < image + 1536 )); do tot=$(( tot * 2 )); done
printf 'built %s (image %s, dom_data %s)\n' "$OUT_DOM" "$image" "$(( tot - image - 1536 ))"

"$GUEST_CC" -O2 "${HOST_FLAGS[@]}" -o "$OUT_HOST" "$RUNTIME_DIR/hostcall_host.c" "$LIBCAPSTONE_C"
printf 'built %s\n' "$OUT_HOST"
