#!/usr/bin/env bash
# Build reference mruby as a pure-capability domain, running precompiled bytecode.
#
# Needs an mruby tree that has ALREADY been built for the host, because two of
# its inputs are generated by mruby's own build system and are target
# independent: build/host/mrblib/mrblib.c (the Ruby-level standard library, as
# bytecode) and build/host/include/mruby/presym/ (the symbol tables). Produce
# them with `rake` in the mruby tree; this script does not reimplement that.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/../../tests/capstone-test-env.sh"

REPO_ROOT=$CAPSTONE_REPO_ROOT
CLANG=${CAPSTONE_CLANG:?}
LD_LLD=${CAPSTONE_LD_LLD:?}
OUT_DIR=${OUT_DIR:-$CAPSTONE_TMP_ROOT/musl-capstone-mruby}
OBJ_DIR="$OUT_DIR/obj"
OUT_DOM=${OUT_DOM:-$OUT_DIR/mruby_probe.dom}
OUT_HOST=${OUT_HOST:-$OUT_DIR/mruby_probe.user}

RUNTIME_DIR="$SCRIPT_DIR/../runtime"
LINKER_SCRIPT="$REPO_ROOT/capstone/my_first_domain/link.ld"
GUEST_CC=${GUEST_CC:-$CAPSTONE_BUILDROOT_DIR/build/host/bin/riscv64-buildroot-linux-gnu-gcc}
LIBCAPSTONE_C="$REPO_ROOT/capstone/caplifive-buildroot/package/modcapstone/userspace/lib/libcapstone.c"
SETJMP_SRC="$REPO_ROOT/xlang/lua-cdp/capstone-lua/capstone_setjmp.S"

ARCHIVE=${ARCHIVE:-$CAPSTONE_TMP_ROOT/musl-capstone-build/libc-capstone.a}
MUSL_SRC_DIR=${MUSL_SRC_DIR:-$CAPSTONE_TMP_ROOT/musl-src/musl-1.2.5}
MRUBY_SRC=${MRUBY_SRC:-$HOME/cheri/mruby-purecap}

NEEDED=("$ARCHIVE" "$MUSL_SRC_DIR/arch/capstone64/syscall_arch.h" "$SETJMP_SRC"
        "$MRUBY_SRC/src/vm.c" "$MRUBY_SRC/build/host/mrblib/mrblib.c"
        "$MRUBY_SRC/build/host/bin/mrbc")

# The generated symbol tables are required ONLY BY TREES THAT HAVE PRESYM, which
# mruby gained in 3.0. The corpus pins nine versions spanning 2017-2026 and most
# of them predate it, so demanding the table unconditionally rejected a perfectly
# buildable tree with "missing prerequisite" -- a prerequisite it has no concept
# of. Keyed on the tree's own header rather than on a version number, because the
# version is not what the compile actually depends on. A tree that DOES need the
# table and lacks it still fails, loudly, on the missing include.
[[ -f "$MRUBY_SRC/include/mruby/presym.h" ]] && \
  NEEDED+=("$MRUBY_SRC/build/host/include/mruby/presym/id.h")

for needed in "${NEEDED[@]}"; do
  [[ -e "$needed" ]] || { echo "missing prerequisite: $needed" >&2; exit 2; }
done

# THE FOUR CONFIG MACROS, all upstream-supported, each forced by this machine:
#
#   MRB_NO_BOXING           boxing_word.h packs an mrb_value into one 64-bit
#                           word by tagging the pointer; its static assert fails
#                           outright with 16-byte pointers. This one is ours --
#                           the CHERI port did not need it.
#   MRB_NO_DIRECT_THREADING the VM's computed-goto dispatch is a second,
#                           independent absolute-addressed jump table, the same
#                           mechanism Lua needed LUA_USE_JUMPTABLE=0 for.
#   POOL_ALIGNMENT=16       the parser pool hands out 8-aligned cells whose
#                           node* fields are 16-byte capabilities.
#   MRB_USE_METHOD_T_STRUCT the method table otherwise stores a tagged pointer.
#
# The last two come from the CHERI port (xlang/cheri/mruby-port/README.md) and
# are about pointer WIDTH, which is why they carry over; its TLS flags do not,
# because a domain has no dynamic linker.
#
# MRB_NO_STDIO: not because stdio is missing -- printf works now -- but because
# this first probe is the VM alone. Adding mruby-print is the next step.
MRUBY_FLAGS=(
  -target capstone64-unknown-elf
  -Xclang -target-feature -Xclang +m
  -Xclang -target-feature -Xclang +a
  -nostdinc -ffreestanding -fno-builtin
  -fno-optimize-sibling-calls -fno-jump-tables
  -D_XOPEN_SOURCE=700
  -DMRB_NO_BOXING -DMRB_NO_DIRECT_THREADING -DMRB_NO_STDIO
  -DPOOL_ALIGNMENT=16 -DMRB_USE_METHOD_T_STRUCT
  # mrb_alignas RAISED TO AT LEAST 16, not overridden to it.
  #
  # mruby 3.4 annotates its static RProc objects `mrb_alignas(8)` so the low
  # three bits of the pointer stay free. A struct holding capabilities already
  # needs 16, and asking for LESS than the natural alignment is an error:
  #   "requested alignment is less than minimum alignment of 16 for type
  #    'const struct RProc'"
  # The intent is a floor, so a floor is what this expresses; a tree that ever
  # asks for 32 keeps its 32. common.h defines the macro under `#ifndef`, so a
  # command-line definition simply wins and no header shadow is needed. Only the
  # two newest pinned trees use it, always with 8 (checked, not assumed).
  "-Dmrb_alignas(n)=__attribute__((aligned(((n)<16)?16:(n))))"
  # MRUBY_PROBE_STACK_DOUBLING=1 adds -DMRB_STACK_EXTEND_DOUBLING, an upstream
  # mruby option. It is DIAGNOSTIC and must not be on for a published number:
  # mruby's default is LINEAR stack growth, chosen because it "saves memory on
  # small devices" -- true of the live set, and exactly wrong for an allocator
  # that never reclaims, where the cumulative carve is the sum of every stack
  # size ever allocated and linear growth makes that sum quadratic. Turning it
  # on separates "the arena is too small for this workload" from "the workload
  # stops for some other reason".
  ${MRUBY_PROBE_STACK_DOUBLING:+-DMRB_STACK_EXTEND_DOUBLING}
  # musl's <math.h> classify macros end in a long-double arm that -O0 does not
  # fold away, so numeric.c and fmt_fp.c pull __signbitl, __fpclassifyl and
  # __extenddftf2, none of which exist (C-20). A -D on this command line does
  # NOT work -- math.h redefines the same names later. The header explains why
  # a forced include does.
  -include "$SCRIPT_DIR/../libc-ext/capstone-math-double.h"
  # FIRST, so the shadowed copy of string.h below wins over the tree's.
  -I"$OBJ_DIR/hdr"
  -I"$MRUBY_SRC/include" -I"$MRUBY_SRC/build/host/include"
  -I"$MUSL_SRC_DIR/arch/capstone64" -I"$MUSL_SRC_DIR/arch/generic"
  -I"$MUSL_SRC_DIR/obj/include" -I"$MUSL_SRC_DIR/include"
  -ffunction-sections -fdata-sections
  -O0 -w -Wno-int-conversion -Wno-error=int-conversion
)

rm -rf "$OBJ_DIR"; mkdir -p "$OBJ_DIR"

# The EMBEDDED-STRING length field, widened in a SHADOW of the headers.
#
# mruby keeps a short string inside the object header with its length in a
# bitfield of `flags`. The capacity derives from sizeof(void*) and so grows with
# the pointer while the field does not; at 16-byte capabilities it no longer
# fits and src/string.c stops the build with "pointer size too big for embedded
# string". patch-embed-len.py has the derivation, both layout schemes, and the
# reason for widening rather than capping the capacity.
#
# It is the SECOND source change the port needs, alongside the parse.y line, and
# it is easy to miss because `mruby-purecap` already carries it: that tree
# differs from its pinned upstream commit by this one line and nothing else, so
# building against it hides the requirement entirely. Row 4 found it.
#
# Shadowed, not patched into the corpus tree, because `xlang/repro/<n>/mruby` is
# the corpus's pinned artefact and must stay byte-identical -- same reason
# patch-parser.py writes into the build directory. -D cannot do this job: the
# header defines the macro unconditionally and would simply override it.
#
# The WHOLE header directory is copied, not just string.h: mruby's headers
# include each other by bare name (`#include "common.h"`), which resolves
# relative to the INCLUDING file, so a lone shadowed header sits in a directory
# with no siblings and fails to find them.
mkdir -p "$OBJ_DIR/hdr"
STRING_C_GEN=""
if [[ -f "$MRUBY_SRC/include/mruby/string.h" ]]; then
  cp -r "$MRUBY_SRC/include/mruby" "$OBJ_DIR/hdr/mruby"
  embed_out=$(python3 "$SCRIPT_DIR/patch-embed-len.py" \
                      "$MRUBY_SRC" "$OBJ_DIR/hdr/mruby/string.h" "$OBJ_DIR/gen") || exit 2
  # Older trees also write the width out as a literal in a static assert, so
  # they need src/string.c shadowed as well; the script says so on stdout.
  [[ $embed_out == SHADOW_SRC=* ]] && STRING_C_GEN=${embed_out#SHADOW_SRC=}
fi

OBJS=()

# The Ruby chunk, compiled to bytecode BY THE HOST mrbc and emitted as a C
# array. This is the step that keeps the parser out of the domain.
"$MRUBY_SRC/build/host/bin/mrbc" -B probe_irep -o "$OBJ_DIR/probe_irep.c" \
                                 "$SCRIPT_DIR/probe.rb"

# STAGE 7 needs a LADDER of ireps rather than one: the fault is inside
# mrb_top_run, and an interpreter loop does not decompose by call structure. It
# decomposes by BYTECODE, so each rung is a slightly larger Ruby chunk and the
# last rung that returns names the construct. All six go into ONE image.
if [[ ${MRUBY_PROBE_STAGE:-0} -ge 7 ]]; then
  : > "$OBJ_DIR/ladder_ireps.c"
  for rb in "$SCRIPT_DIR"/ladder/*.rb; do
    sym="ladder_$(basename "$rb" .rb)"
    "$MRUBY_SRC/build/host/bin/mrbc" -B "$sym" -o "$OBJ_DIR/$sym.c" "$rb"
    cat "$OBJ_DIR/$sym.c" >> "$OBJ_DIR/ladder_ireps.c"
  done
fi

"$CLANG" -target capstone64-unknown-elf -Xclang -target-feature -Xclang +m \
  -ffreestanding -O0 -c "$RUNTIME_DIR/start-musl.S" -o "$OBJ_DIR/start-musl.o"
OBJS+=("$OBJ_DIR/start-musl.o")

"$CLANG" -target capstone64-unknown-elf -Xclang -target-feature -Xclang +m \
  -ffreestanding -O0 -c "$SETJMP_SRC" -o "$OBJ_DIR/setjmp.o"
OBJS+=("$OBJ_DIR/setjmp.o")

# MRUBY_PROBE_REVOKE=1 swaps the libc allocator for the REVOKING one: every
# allocation is an independently revocable SPLIT off a host-granted linear
# arena, and free() revokes it. That is the configuration a security number may
# be measured on; libc-ext/malloc.c is not, and says so itself.
#
# revoke_arena_domain.c defines malloc/free/realloc, and our objects precede the
# archive on the link line, so libc-ext/malloc.c is simply never pulled. The
# host program needs the same macro: it has to create and transfer a third
# region, and share order is capture order.
ARENA_FLAGS=()
HOST_FLAGS=()
if [[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]]; then
  ARENA_FLAGS=(-DCAPSTONE_DOMAIN_ARENA)
  HOST_FLAGS=(-DCAPSTONE_DOMAIN_ARENA)
fi

# MRUBY_PROBE_ARENA_MB makes the arena size a VARIABLE rather than a constant to
# be edited by hand. It is the thing most likely to be the reason a workload
# stops early, because the revoking allocator never coalesces: the arena has to
# hold the whole CUMULATIVE carve, not the live set. Only meaningful with
# MRUBY_PROBE_REVOKE=1; the host and the domain must agree, and they do because
# both read this one variable.
if [[ -n ${MRUBY_PROBE_ARENA_MB:-} ]]; then
  HOST_FLAGS+=(-DHC_HOST_ARENA_SIZE="(${MRUBY_PROBE_ARENA_MB}UL * 1024 * 1024)")
fi

"$CLANG" "${MRUBY_FLAGS[@]}" "${ARENA_FLAGS[@]}" -c "$RUNTIME_DIR/hostcall.c" \
         -o "$OBJ_DIR/hostcall.o"
OBJS+=("$OBJ_DIR/hostcall.o")

if [[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]]; then
  "$CLANG" "${MRUBY_FLAGS[@]}" "${ARENA_FLAGS[@]}" \
    -I"$REPO_ROOT/capstone/benchmarks/sqlite" \
    -c "$REPO_ROOT/xlang/common/revoke_arena_domain.c" -o "$OBJ_DIR/revoke_arena.o"
  OBJS+=("$OBJ_DIR/revoke_arena.o")
fi

# -U__GNUC__ for hash.c ONLY: ib_capa_to_bit calls __builtin_ctz, which crashes
# the backend (ISSUES.md C-24). Undefining __GNUC__ selects mruby's own de
# Bruijn fallback, written for compilers without the builtin. Per file, because
# y.tab.c needs __GNUC__ for alloca -- not that this build compiles y.tab.c.
# src/fmt_fp.c NARROWED to double where the tree still uses long double.
#
# `long double` is binary128 on this target and so is a capability, so it does
# not merely fail to link (C-20) -- it CRASHES the compiler, with an APInt
# assertion and therefore no source location:
#
#   clang: llvm/include/llvm/ADT/APInt.h:1565: getSExtValue():
#          Assertion `getSignificantBits() <= 64' failed.
#
# Seven of the nine pinned corpus trees are affected and all seven only in this
# one file; upstream mruby dropped long double from it by 2022.
#
# NARROWING IS SOUND HERE, and specifically: the only caller is `fmt_core`, which
# passes `mrb_float` -- a double. The value is widened to long double for the
# call and immediately narrowed back inside, so removing the parameter's width
# removes a round trip rather than precision. The algorithm itself is musl's,
# expanding the mantissa into uint32 limbs and doing base-1e9 long division, and
# LDBL_MANT_DIG only sizes that limb array.
#
# Reusing libc-ext/gen-vfprintf-double.py rather than a second transform: it is
# the same substitution on the same algorithm, and it FAILS LOUDLY if any
# 128-bit reference survives.
FMT_FP_SRC="$MRUBY_SRC/src/fmt_fp.c"
FMT_FP_GEN=""
if [[ -f $FMT_FP_SRC ]] && grep -q "long double" "$FMT_FP_SRC"; then
  FMT_FP_GEN="$OBJ_DIR/gen/fmt_fp.c"
  python3 "$SCRIPT_DIR/../libc-ext/gen-vfprintf-double.py" \
          "$MUSL_SRC_DIR" "$FMT_FP_GEN" --source "$FMT_FP_SRC"
fi

for src in "$MRUBY_SRC"/src/*.c "$MRUBY_SRC/build/host/mrblib/mrblib.c"; do
  base=$(basename "$src" .c)
  extra=()
  [[ $base == hash ]] && extra=(-U__GNUC__)
  [[ $base == fmt_fp && -n $FMT_FP_GEN ]] && src=$FMT_FP_GEN
  [[ $base == string && -n $STRING_C_GEN ]] && src=$STRING_C_GEN
  "$CLANG" "${MRUBY_FLAGS[@]}" "${extra[@]}" -c "$src" -o "$OBJ_DIR/mrb_$base.o"
  OBJS+=("$OBJ_DIR/mrb_$base.o")
done

# MRUBY_WITH_PARSER=1 adds the compiler gem, so the domain evaluates Ruby SOURCE
# instead of only precompiled bytecode. Off by default, and the order matters:
# the bytecode variant is the smaller image and it separates "does the VM run"
# from "does the parser run". Answering both in one image would leave a failure
# ambiguous between them.
PROBE_EXTRA=()
[[ ${MRUBY_PROBE_REVOKE:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_REVOKE)
# MRUBY_PROBE_CDP=1 runs the corpus's largest mechanism class on the real
# interpreter; MRUBY_PROBE_CDP_CONTROL=1 is its matched arm with revocation off.
[[ ${MRUBY_PROBE_CDP:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_CDP)
[[ ${MRUBY_PROBE_CDP_CONTROL:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_CDP_CONTROL)
# MRUBY_PROBE_ROW=<n> runs xlang corpus row <n>'s OWN trigger.rb, embedded
# verbatim. Only rows whose pinned mruby version matches MRUBY_SRC are
# meaningful; row 10's pinned commit is the tree this port was validated on.
# MRUBY_PROBE_GEMS="eval hash-ext" links those mrbgems and generates the
# mrb_init_mrbgems the probe otherwise stubs out. Corpus triggers need them:
# row 9's first line is `eval(...)`, which is not core mruby at all, and without
# the gem the trigger raises NoMethodError before reaching its offending access
# -- a run where both arms report identically and neither means anything.
#
# Gems with an mrblib half need mrbc and a generated loader; that is NOT built
# here, so such a gem is refused loudly rather than half-linked.
if [[ -n ${MRUBY_PROBE_GEMS:-} ]]; then
  GEM_INIT="$OBJ_DIR/gem_init.c"
  {
    echo '/* GENERATED by build-mruby-probe.sh -- do not edit. */'
    echo '#include <mruby.h>'
  } > "$GEM_INIT"
  for gem in $MRUBY_PROBE_GEMS; do
    GEM_DIR="$MRUBY_SRC/mrbgems/mruby-$gem"
    [[ -d "$GEM_DIR/src" ]] || { echo "no such gem: mruby-$gem" >&2; exit 2; }
    if compgen -G "$GEM_DIR/mrblib/*.rb" > /dev/null; then
      echo "mruby-$gem has an mrblib half, which this build cannot generate" >&2
      exit 2
    fi
    sym="mrb_mruby_${gem//-/_}_gem_init"
    for gsrc in "$GEM_DIR"/src/*.c; do
      gbase=$(basename "$gsrc" .c)
      "$CLANG" "${MRUBY_FLAGS[@]}" -I"$MRUBY_SRC/mrbgems/mruby-compiler/core" \
               -c "$gsrc" -o "$OBJ_DIR/gem_${gem//-/_}_$gbase.o"
      OBJS+=("$OBJ_DIR/gem_${gem//-/_}_$gbase.o")
    done
    echo "void $sym(mrb_state *mrb);" >> "$GEM_INIT"
  done
  {
    echo 'void mrb_init_mrbgems(mrb_state *mrb) {'
    for gem in $MRUBY_PROBE_GEMS; do
      echo "  mrb_mruby_${gem//-/_}_gem_init(mrb);"
    done
    echo '}'
    echo 'void mrb_final_mrbgems(mrb_state *mrb) { (void)mrb; }'
  } >> "$GEM_INIT"
  "$CLANG" "${MRUBY_FLAGS[@]}" -c "$GEM_INIT" -o "$OBJ_DIR/gem_init.o"
  OBJS+=("$OBJ_DIR/gem_init.o")
  PROBE_EXTRA+=(-DMRUBY_PROBE_GEMS)
fi

if [[ -n ${MRUBY_PROBE_ROW:-} ]]; then
  ROW_RB="$REPO_ROOT/xlang/repro/${MRUBY_PROBE_ROW}/trigger.rb"
  python3 "$SCRIPT_DIR/embed-ruby.py" "$ROW_RB" "$OBJ_DIR/row_trigger.c" row_trigger
  PROBE_EXTRA+=(-DMRUBY_PROBE_ROW="${MRUBY_PROBE_ROW}")
fi
# MRUBY_PROBE_BUMP=1 swaps the probe's allocator for an O(1) bump arena. See the
# comment in mruby_probe.c: it is the matched arm for a wedge, differing from the
# libc allocator in exactly one property.
[[ ${MRUBY_PROBE_BUMP:-0} == 1 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_BUMP)
# MRUBY_PROBE_STAGE=N builds one arm of the staged batch: 1 allocates the state,
# 2 adds mrb_gc_init, 3 adds mrb_init_core, 0 (default) is the full run. Each arm
# RETURNS a marker instead of running to the failure, so a wedge costs only the
# arms after it. See run-mruby-stages.sh.
[[ ${MRUBY_PROBE_STAGE:-0} != 0 ]] && PROBE_EXTRA+=(-DMRUBY_PROBE_STAGE="${MRUBY_PROBE_STAGE}")
if [[ ${MRUBY_WITH_PARSER:-0} == 1 ]]; then
  # y.tab.c is GENERATED from parse.y, and where rake leaves it moved: newer
  # trees keep it beside the source, older ones only under build/host. Both are
  # checked, source first, and a tree with neither fails loudly rather than
  # silently building without a parser.
  PARSER_SRC="$MRUBY_SRC/mrbgems/mruby-compiler/core"
  PARSER_GEN="$MRUBY_SRC/build/host/mrbgems/mruby-compiler/core"
  if [[ -f "$PARSER_SRC/y.tab.c" ]]; then
    PARSER_CORE="$PARSER_SRC"
  elif [[ -f "$PARSER_GEN/y.tab.c" ]]; then
    PARSER_CORE="$PARSER_GEN"
  else
    echo "no y.tab.c in $PARSER_SRC or $PARSER_GEN; run rake in $MRUBY_SRC" >&2
    exit 2
  fi
  python3 "$SCRIPT_DIR/patch-parser.py" "$PARSER_CORE/y.tab.c" \
          "$OBJ_DIR/y.tab.fixed.c"
  # codegen.c always lives with the SOURCE, even when y.tab.c does not, and both
  # include headers from the source directory.
  "$CLANG" "${MRUBY_FLAGS[@]}" -I"$PARSER_CORE" -I"$PARSER_SRC" \
           -c "$OBJ_DIR/y.tab.fixed.c" -o "$OBJ_DIR/mrb_parser.o"
  "$CLANG" "${MRUBY_FLAGS[@]}" -I"$PARSER_CORE" -I"$PARSER_SRC" \
           -c "$PARSER_SRC/codegen.c" -o "$OBJ_DIR/mrb_codegen.o"
  OBJS+=("$OBJ_DIR/mrb_parser.o" "$OBJ_DIR/mrb_codegen.o")
  PROBE_EXTRA+=(-DMRUBY_PROBE_PARSER)   # += : the bump flag must survive
fi

"$CLANG" "${MRUBY_FLAGS[@]}" "${PROBE_EXTRA[@]}" -I"$OBJ_DIR" \
         -c "$SCRIPT_DIR/mruby_probe.c" -o "$OBJ_DIR/mruby_probe.o"
OBJS+=("$OBJ_DIR/mruby_probe.o")

"$LD_LLD" --gc-sections -T "$LINKER_SCRIPT" -o "$OUT_DOM" "${OBJS[@]}" "$ARCHIVE"

image=$("$CAPSTONE_LLVM_READOBJ" --program-headers "$OUT_DOM" \
         | awk '/MemSize/ {print $2; exit}')
tot=4096; while (( tot < image + 1536 )); do tot=$(( tot * 2 )); done
printf 'built %s (image %s, dom_data %s)\n' "$OUT_DOM" "$image" "$(( tot - image - 1536 ))"

"$GUEST_CC" -O2 "${HOST_FLAGS[@]}" -o "$OUT_HOST" "$RUNTIME_DIR/hostcall_host.c" "$LIBCAPSTONE_C"
printf 'built %s\n' "$OUT_HOST"
