add_subdirectory("${CAPSTONE_REPO_ROOT}/capstone/runtime" "${CMAKE_BINARY_DIR}/runtime")
set(WM_SHARED src/shared/scopes.c src/shared/freestanding.c)
# The backing policy is the one part that differs per platform: Capstone
# regions with Sublet handles, a native bump, or PoisonCap-mapped regions.
set(WM_BACKING src/shared/backing.c)
if(PORT_PLATFORM STREQUAL "cheribsd")
  option(WM_POISONCAP "PoisonCap lifetimes on CheriBSD" OFF)
  if(WM_POISONCAP)
    set(WM_BACKING src/cheribsd/poisoncap.c)
  endif()
endif()
function(wm_executable name variant)
  set(workload ${ARGN})
  set(source "${CMAKE_BINARY_DIR}/source-${variant}")
  wm_upstream_units(upstream ${variant})
  if(PORT_HOSTED)
    set(platform src/native/main.c src/native/regions.c ${WM_BACKING})
  else()
    set(platform src/capstone-domain/entry.c src/allocators/sublet/regions.c
      "${CAPSTONE_REPO_ROOT}/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c"
      "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/start.S"
      "${CAPSTONE_REPO_ROOT}/capstone/tests/runtime-qemu/gct-section-end.S"
      src/shared/backing.c)
  endif()
  add_executable(${name} ${platform} ${workload} ${WM_SHARED} ${upstream})
  add_dependencies(${name} source-${variant})
  # The shim directory shadows glib.h and the ws_* headers the upstream units include.
  target_include_directories(${name} PRIVATE src/shared/shim src/shared "${source}/wsutil/wmem")
  target_compile_definitions(${name} PRIVATE WMEM_PORT_HOOKS)
  if(WM_POISONCAP)
    target_compile_definitions(${name} PRIVATE WM_POISONCAP)
    target_include_directories(${name} PRIVATE src/cheribsd)
  endif()
  target_compile_options(${name} PRIVATE -Wall -Wextra -ffunction-sections -fdata-sections)
  target_link_libraries(${name} PRIVATE Capstone::Runtime)
  if(NOT PORT_HOSTED)
    target_compile_definitions(${name} PRIVATE WM_DOMAIN)
    set(link_script "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/link.ld")
    target_link_options(${name} PRIVATE --gc-sections -T "${link_script}")
    set_target_properties(${name} PROPERTIES SUFFIX .dom LINK_DEPENDS "${link_script}")
  endif()
endfunction()
if(NOT PORT_HOSTED)
  enable_language(ASM)
endif()
wm_source(ported)
wm_executable(replay ported src/shared/replay.c)
if(PORT_HOSTED)
  wm_upstream_units(upstream_ported ported)
  add_library(wireshark-wmem STATIC src/native/regions.c ${WM_BACKING} ${WM_SHARED} ${upstream_ported})
  add_dependencies(wireshark-wmem source-ported)
  target_include_directories(wireshark-wmem PUBLIC src/shared/shim src/shared
    "${CMAKE_BINARY_DIR}/source-ported/wsutil/wmem")
  target_compile_definitions(wireshark-wmem PUBLIC WMEM_PORT_HOOKS)
  if(WM_POISONCAP)
    target_compile_definitions(wireshark-wmem PUBLIC WM_POISONCAP)
    target_include_directories(wireshark-wmem PUBLIC src/cheribsd)
  endif()
  if(PORT_PLATFORM STREQUAL "cheribsd")
    # The corpus arms run under a supervisor that reports the child's fault
    # from outside it and resolves the labelled probe from the child's map.
    add_executable(supervise
      "${CAPSTONE_REPO_ROOT}/capstone/bug-corpora/cpython/pymalloc-repros/observe/supervise.c")
    target_compile_definitions(supervise PRIVATE PROBE_SYMBOL="wm_defect_probe")
    target_link_libraries(supervise PRIVATE util)
  endif()
  target_link_libraries(wireshark-wmem PUBLIC Capstone::Runtime)
  add_library(Wireshark::Wmem ALIAS wireshark-wmem)
  add_executable(allocator-example examples/wmem.c)
  target_link_libraries(allocator-example PRIVATE Wireshark::Wmem)
  include("${PORT_SUPPORT_ROOT}/cmake/Client.cmake")
  port_add_client(Wireshark::Wmem)
  wm_source(reference)
  wm_executable(replay-reference reference src/shared/replay.c)
else()
  wm_executable(wmem-security ported security-tests/shared/lifetimes.c)
endif()
# The defect corpus: one program per NN_*/case.c, named as the contract names
# run artifacts. Case material lives in bug-corpora, not inside the port.
set(WM_CORPUS_DIR "" CACHE PATH "Defect corpus root holding NN_*/case.c programs")
function(wm_corpus_cases dirs_out stems_out)
  set(dirs "")
  set(stems "")
  if(WM_CORPUS_DIR)
    file(GLOB found CONFIGURE_DEPENDS "${WM_CORPUS_DIR}/[0-9][0-9]_*")
    foreach(dir ${found})
      if(IS_DIRECTORY "${dir}" AND EXISTS "${dir}/case.c")
        get_filename_component(name "${dir}" NAME)
        string(REGEX REPLACE "^([0-9][0-9])_[^_]+_(.*)$" "\\1;\\2" parts "${name}")
        list(GET parts 0 num)
        list(GET parts 1 slug)
        string(REPLACE "_" "-" slug "${slug}")
        list(APPEND dirs "${dir}")
        list(APPEND stems "${num}-${slug}")
      endif()
    endforeach()
  endif()
  set(${dirs_out} "${dirs}" PARENT_SCOPE)
  set(${stems_out} "${stems}" PARENT_SCOPE)
endfunction()
wm_corpus_cases(wm_dirs wm_stems)
list(LENGTH wm_dirs wm_case_count)
if(WM_CORPUS_DIR AND wm_case_count EQUAL 0)
  message(FATAL_ERROR "WM_CORPUS_DIR=${WM_CORPUS_DIR} holds no NN_*/case.c; a corpus that builds nothing must not look like a corpus that passed")
endif()
if(wm_case_count GREATER 0)
  math(EXPR wm_last "${wm_case_count} - 1")
  foreach(i RANGE 0 ${wm_last})
    list(GET wm_dirs ${i} wm_dir)
    list(GET wm_stems ${i} wm_stem)
    if(PORT_HOSTED)
      add_executable("${wm_stem}" "${wm_dir}/case.c" "${WM_CORPUS_DIR}/shared/driver.c")
      target_include_directories("${wm_stem}" PRIVATE "${WM_CORPUS_DIR}/shared")
      target_compile_definitions("${wm_stem}" PRIVATE WM_CORPUS_HOSTED)
      target_link_libraries("${wm_stem}" PRIVATE Wireshark::Wmem)
    else()
      wm_executable("${wm_stem}" ported "${wm_dir}/case.c" "${WM_CORPUS_DIR}/shared/driver.c")
      target_include_directories("${wm_stem}" PRIVATE "${WM_CORPUS_DIR}/shared")
    endif()
  endforeach()
  message(STATUS "wmem defect corpus: ${wm_case_count} cases")
endif()
