add_subdirectory("${CAPSTONE_REPO_ROOT}/capstone/runtime" "${CMAKE_BINARY_DIR}/runtime")
# wmem as released everywhere, except the capstone-application build with
# WM_SUBLET, which applies patch 0001. Native also prepares the patched source,
# for the source-preparation test; nothing native compiles it.
if(WM_SUBLET)
  set(WM_VARIANT sublet)
else()
  set(WM_VARIANT reference)
endif()
wm_source(${WM_VARIANT})
if(PORT_PLATFORM STREQUAL "native")
  wm_source(sublet)
endif()
wm_upstream_units(wm_units ${WM_VARIANT})
add_library(wireshark-wmem STATIC ${wm_units}
  src/shared/system.c src/shared/compat.c src/shared/scopes.c)
add_dependencies(wireshark-wmem source-${WM_VARIANT})
# The shim directory shadows glib.h and the ws_* headers the upstream units include.
target_include_directories(wireshark-wmem PUBLIC src/shared/shim src/shared
  "${CMAKE_BINARY_DIR}/source-${WM_VARIANT}/wsutil/wmem")
target_compile_options(wireshark-wmem PRIVATE -Wall -Wextra -ffunction-sections -fdata-sections)
target_link_libraries(wireshark-wmem PUBLIC Capstone::Runtime)
add_library(Wireshark::Wmem ALIAS wireshark-wmem)
add_executable(replay src/shared/main.c src/shared/replay.c)
target_link_libraries(replay PRIVATE Wireshark::Wmem)
add_executable(allocator-example examples/wmem.c)
target_link_libraries(allocator-example PRIVATE Wireshark::Wmem)
include("${PORT_SUPPORT_ROOT}/cmake/Client.cmake")
port_add_client(Wireshark::Wmem)
if(PORT_PLATFORM STREQUAL "cheribsd")
  # The corpus arms run under a supervisor that reports the child's fault
  # from outside it and resolves the labelled probe from the child's map.
  add_executable(supervise
    "${CAPSTONE_REPO_ROOT}/capstone/bug-corpora/cpython/pymalloc-repros/observe/supervise.c")
  target_compile_definitions(supervise PRIVATE PROBE_SYMBOL="wm_defect_probe")
  target_link_libraries(supervise PRIVATE util)
endif()
# The defect corpus: one program per NN_*/case.c, named as the contract names
# run artifacts. Case material lives in bug-corpora, not inside the port.
set(WM_CORPUS_DIR "" CACHE PATH "Defect corpus root holding NN_*/case.c programs")
function(wm_corpus_cases dirs_out stems_out)
  set(dirs "")
  set(stems "")
  if(WM_CORPUS_DIR)
    file(GLOB found CONFIGURE_DEPENDS "${WM_CORPUS_DIR}/[0-9][0-9]_*")
    foreach(dir ${found})
      if(IS_DIRECTORY "${dir}" AND EXISTS "${dir}/case.c")
        get_filename_component(name "${dir}" NAME)
        string(REGEX REPLACE "^([0-9][0-9])_[^_]+_(.*)$" "\\1;\\2" parts "${name}")
        list(GET parts 0 num)
        list(GET parts 1 slug)
        string(REPLACE "_" "-" slug "${slug}")
        list(APPEND dirs "${dir}")
        list(APPEND stems "${num}-${slug}")
      endif()
    endforeach()
  endif()
  set(${dirs_out} "${dirs}" PARENT_SCOPE)
  set(${stems_out} "${stems}" PARENT_SCOPE)
endfunction()
wm_corpus_cases(wm_dirs wm_stems)
list(LENGTH wm_dirs wm_case_count)
if(WM_CORPUS_DIR AND wm_case_count EQUAL 0)
  message(FATAL_ERROR "WM_CORPUS_DIR=${WM_CORPUS_DIR} holds no NN_*/case.c; a corpus that builds nothing must not look like a corpus that passed")
endif()
if(wm_case_count GREATER 0)
  math(EXPR wm_last "${wm_case_count} - 1")
  foreach(i RANGE 0 ${wm_last})
    list(GET wm_dirs ${i} wm_dir)
    list(GET wm_stems ${i} wm_stem)
    add_executable("${wm_stem}" "${wm_dir}/case.c" "${WM_CORPUS_DIR}/shared/driver.c")
    target_include_directories("${wm_stem}" PRIVATE "${WM_CORPUS_DIR}/shared")
    target_link_libraries("${wm_stem}" PRIVATE Wireshark::Wmem)
  endforeach()
  message(STATUS "wmem defect corpus: ${wm_case_count} cases")
endif()
