add_subdirectory("${CAPSTONE_REPO_ROOT}/capstone/runtime" "${CMAKE_BINARY_DIR}/runtime")
set(WM_SHARED src/shared/backing.c src/shared/scopes.c src/shared/freestanding.c)
function(wm_executable name variant workload)
  set(source "${CMAKE_BINARY_DIR}/source-${variant}")
  wm_upstream_units(upstream ${variant})
  if(PORT_HOSTED)
    set(platform src/native/main.c src/native/regions.c)
  else()
    set(platform src/capstone-domain/entry.c src/allocators/sublet/regions.c
      "${CAPSTONE_REPO_ROOT}/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c"
      "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/start.S"
      "${CAPSTONE_REPO_ROOT}/capstone/tests/runtime-qemu/gct-section-end.S")
  endif()
  add_executable(${name} ${platform} ${workload} ${WM_SHARED} ${upstream})
  add_dependencies(${name} source-${variant})
  # The shim directory shadows glib.h and the ws_* headers the upstream units include.
  target_include_directories(${name} PRIVATE src/shared/shim src/shared "${source}/wsutil/wmem")
  target_compile_definitions(${name} PRIVATE WMEM_PORT_HOOKS)
  target_compile_options(${name} PRIVATE -Wall -Wextra -ffunction-sections -fdata-sections)
  target_link_libraries(${name} PRIVATE Capstone::Runtime)
  if(NOT PORT_HOSTED)
    target_compile_definitions(${name} PRIVATE WM_DOMAIN)
    set(link_script "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/link.ld")
    target_link_options(${name} PRIVATE --gc-sections -T "${link_script}")
    set_target_properties(${name} PROPERTIES SUFFIX .dom LINK_DEPENDS "${link_script}")
  endif()
endfunction()
if(NOT PORT_HOSTED)
  enable_language(ASM)
endif()
wm_source(ported)
wm_executable(replay ported src/shared/replay.c)
if(PORT_HOSTED)
  wm_upstream_units(upstream_ported ported)
  add_library(wireshark-wmem STATIC src/native/regions.c ${WM_SHARED} ${upstream_ported})
  add_dependencies(wireshark-wmem source-ported)
  target_include_directories(wireshark-wmem PUBLIC src/shared/shim src/shared
    "${CMAKE_BINARY_DIR}/source-ported/wsutil/wmem")
  target_compile_definitions(wireshark-wmem PUBLIC WMEM_PORT_HOOKS)
  target_link_libraries(wireshark-wmem PUBLIC Capstone::Runtime)
  add_library(Wireshark::Wmem ALIAS wireshark-wmem)
  add_executable(allocator-example examples/wmem.c)
  target_link_libraries(allocator-example PRIVATE Wireshark::Wmem)
  include("${PORT_SUPPORT_ROOT}/cmake/Client.cmake")
  port_add_client(Wireshark::Wmem)
  wm_source(reference)
  wm_executable(replay-reference reference src/shared/replay.c)
else()
  wm_executable(wmem-security ported security-tests/shared/lifetimes.c)
endif()
