# Environment variables provide defaults; -D cache settings take precedence.
function(ffpool_path name fallback description)
  if(DEFINED ENV{${name}} AND NOT "$ENV{${name}}" STREQUAL "")
    set(fallback "$ENV{${name}}")
  endif()
  set(${name} "${fallback}" CACHE PATH "${description}")
endfunction()

set(tmp_root /tmp/capstone)
if(DEFINED ENV{CAPSTONE_TMP_ROOT} AND NOT "$ENV{CAPSTONE_TMP_ROOT}" STREQUAL "")
  set(tmp_root "$ENV{CAPSTONE_TMP_ROOT}")
endif()
ffpool_path(FFPOOL_WORK "${tmp_root}/ffmpeg-buffer-pool" "Archive cache root and conventional runner paths; use -B to relocate a CMake build")
ffpool_path(FFPOOL_NATIVE_BUILD_DIR "${FFPOOL_WORK}/build/native" "Native build used by recording and QEMU tests")
ffpool_path(FFPOOL_DOMAIN_BUILD_DIR "${FFPOOL_WORK}/build/capstone-domain" "Capstone domain build used by QEMU runners")
ffpool_path(FFPOOL_LINUX_BUILD_DIR "${FFPOOL_WORK}/build/linux-host" "Guest Linux loader build used by QEMU runners")
ffpool_path(FFPOOL_RECORDING_DIR "${FFPOOL_NATIVE_BUILD_DIR}/test-results/workload" "Native CTest recording used by QEMU replay tests")
