# One freestanding ABI; each port declares its header provider and ISA needs.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR capstone64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PORT_PLATFORM capstone-domain CACHE STRING "Execution platform" FORCE)
include("${CMAKE_CURRENT_LIST_DIR}/../Workspace.cmake")
set(CMAKE_C_COMPILER "${CAPSTONE_LLVM_BUILD_DIR}/bin/clang")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_C_COMPILER_TARGET capstone64-unknown-elf)
set(CMAKE_ASM_COMPILER_TARGET capstone64-unknown-elf)
set(CMAKE_AR "${CAPSTONE_LLVM_BUILD_DIR}/bin/llvm-ar")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_AR> s <TARGET>")
set(CMAKE_LINKER "${CAPSTONE_LLVM_BUILD_DIR}/bin/ld.lld")

option(PORT_C11_ATOMICS "Enable the atomic ISA required by this port" OFF)
set(PORT_HEADER_PROVIDER application CACHE STRING "application or musl")
set_property(CACHE PORT_HEADER_PROVIDER PROPERTY STRINGS application musl)
# Keep each -Xclang pair intact; option deduplication would change its meaning.
set(CMAKE_C_FLAGS_INIT "-Xclang -target-feature -Xclang +m")
if(PORT_C11_ATOMICS)
  string(APPEND CMAKE_C_FLAGS_INIT " -Xclang -target-feature -Xclang +a")
endif()
string(APPEND CMAKE_C_FLAGS_INIT " -ffreestanding -fno-builtin")
if(PORT_HEADER_PROVIDER STREQUAL "musl")
  port_path(PORT_MUSL_ROOT "${tmp_root}/musl-src/musl-1.2.5" "Prepared Capstone MUSL headers")
  if(NOT EXISTS "${PORT_MUSL_ROOT}/obj/include/bits/alltypes.h")
    message(FATAL_ERROR "Set PORT_MUSL_ROOT to prepared MUSL headers with obj/include/bits/alltypes.h.")
  endif()
  execute_process(COMMAND "${CMAKE_C_COMPILER}" -print-resource-dir
    OUTPUT_VARIABLE resource_dir OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
  string(APPEND CMAKE_C_FLAGS_INIT " -nostdinc")
  foreach(headers arch/capstone64 arch/generic obj/include include)
    string(APPEND CMAKE_C_FLAGS_INIT " -isystem \"${PORT_MUSL_ROOT}/${headers}\"")
  endforeach()
  string(APPEND CMAKE_C_FLAGS_INIT " -isystem \"${resource_dir}/include\"")
elseif(PORT_HEADER_PROVIDER STREQUAL "application")
  string(APPEND CMAKE_C_FLAGS_INIT " -nostdlibinc")
else()
  message(FATAL_ERROR "Unknown PORT_HEADER_PROVIDER: ${PORT_HEADER_PROVIDER}")
endif()
set(CMAKE_ASM_FLAGS_INIT "--target=capstone64-unknown-elf -ffreestanding")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  CAPSTONE_LLVM_BUILD_DIR PORT_C11_ATOMICS PORT_HEADER_PROVIDER PORT_MUSL_ROOT)
