# Shared CHERI-RISC-V purecap target. SDK and rootfs must be a matched pair.
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
foreach(path CHERI_SDK CHERI_SYSROOT)
  if(NOT DEFINED ${path} AND DEFINED ENV{${path}})
    set(${path} "$ENV{${path}}" CACHE PATH "Installed CheriBSD toolchain path")
  endif()
  if(NOT IS_DIRECTORY "${${path}}")
    message(FATAL_ERROR "Set ${path} to a matching installed CHERI SDK/rootfs")
  endif()
endforeach()
set(PORT_PLATFORM cheribsd CACHE STRING "CheriBSD purecap platform" FORCE)
set(CMAKE_C_COMPILER "${CHERI_SDK}/bin/clang")
set(CMAKE_C_COMPILER_TARGET riscv64-unknown-freebsd13)
set(CMAKE_AR "${CHERI_SDK}/bin/llvm-ar")
set(CMAKE_RANLIB "${CHERI_SDK}/bin/llvm-ranlib")
set(CMAKE_SYSROOT "${CHERI_SYSROOT}")
set(CMAKE_C_FLAGS_INIT "-march=rv64imafdcxcheri -mabi=l64pc128d -mno-relax -B${CHERI_SDK}/bin")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CHERI_SDK CHERI_SYSROOT)
set(BUILD_TESTING OFF CACHE BOOL "Run cross-built tests with the CheriBSD runner")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
