function(pg_path name fallback description)
  if(DEFINED ENV{${name}} AND NOT "$ENV{${name}}" STREQUAL "")
    set(fallback "$ENV{${name}}")
  endif()
  set(${name} "${fallback}" CACHE PATH "${description}")
endfunction()
set(tmp_root /tmp/capstone)
if(DEFINED ENV{CAPSTONE_TMP_ROOT} AND NOT "$ENV{CAPSTONE_TMP_ROOT}" STREQUAL "")
  set(tmp_root "$ENV{CAPSTONE_TMP_ROOT}")
endif()
pg_path(PG_WORK "${tmp_root}/postgres-memory-contexts" "Archive cache and conventional runner paths")
pg_path(PG_LINUX_BUILD_DIR "${PG_WORK}/build/linux-host" "Guest Linux loader build")
