/* B1.0 (docs/plans/b0-silicon-delegated-runtime.md): printf on the gp-captable silicon build. GENERATED by
 * gen_b0_printf.py: each expected string is the HOST printf's output for the same call. Exit 0 = every case
 * matched; otherwise the count of mismatches (each printed). */
#include <stdio.h>
#include <string.h>

int main(void)
{
	char b[512];
	int bad = 0;
	snprintf(b, sizeof b, "%d", -12345);
	if (strcmp(b, "-12345")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%d", b, "-12345"); bad++; }
	snprintf(b, sizeof b, "%u", 4000000000U);
	if (strcmp(b, "4000000000")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%u", b, "4000000000"); bad++; }
	snprintf(b, sizeof b, "%x", 3735928559U);
	if (strcmp(b, "deadbeef")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%x", b, "deadbeef"); bad++; }
	snprintf(b, sizeof b, "%08X", 48879U);
	if (strcmp(b, "0000BEEF")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%08X", b, "0000BEEF"); bad++; }
	snprintf(b, sizeof b, "%ld", -9000000000000L);
	if (strcmp(b, "-9000000000000")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%ld", b, "-9000000000000"); bad++; }
	snprintf(b, sizeof b, "%llu", 18446744073709551615ULL);
	if (strcmp(b, "18446744073709551615")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%llu", b, "18446744073709551615"); bad++; }
	snprintf(b, sizeof b, "%s|%-8s|", "abc", "de");
	if (strcmp(b, "abc|de      |")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%s|%-8s|", b, "abc|de      |"); bad++; }
	snprintf(b, sizeof b, "%c%c%c", 'x', 'y', 'z');
	if (strcmp(b, "xyz")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%c%c%c", b, "xyz"); bad++; }
	snprintf(b, sizeof b, "%5d|%-5d|", 42, 42);
	if (strcmp(b, "   42|42   |")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%5d|%-5d|", b, "   42|42   |"); bad++; }
	snprintf(b, sizeof b, "%f", 3.14159265358979);
	if (strcmp(b, "3.141593")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%f", b, "3.141593"); bad++; }
	snprintf(b, sizeof b, "%.3f", -0.0005);
	if (strcmp(b, "-0.001")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%.3f", b, "-0.001"); bad++; }
	snprintf(b, sizeof b, "%e", 6.02214076e+23);
	if (strcmp(b, "6.022141e+23")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%e", b, "6.022141e+23"); bad++; }
	snprintf(b, sizeof b, "%g", 1e-05);
	if (strcmp(b, "1e-05")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%g", b, "1e-05"); bad++; }
	snprintf(b, sizeof b, "%g", 123456789.0);
	if (strcmp(b, "1.23457e+08")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%g", b, "1.23457e+08"); bad++; }
	snprintf(b, sizeof b, "%.10g", 0.6666666666666666);
	if (strcmp(b, "0.6666666667")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%.10g", b, "0.6666666667"); bad++; }
	snprintf(b, sizeof b, "%10.4f|", 2.5);
	if (strcmp(b, "    2.5000|")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%10.4f|", b, "    2.5000|"); bad++; }
	snprintf(b, sizeof b, "%a", 1.0);
	if (strcmp(b, "0x1p+0")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%a", b, "0x1p+0"); bad++; }
	snprintf(b, sizeof b, "%f", 1e+300);
	if (strcmp(b, "1000000000000000052504760255204420248704468581108159154915854115511802457988908195786371375080447864043704443832883878176942523235360430575644792184786706982848387200926575803737830233794788090059368953234970799945081119038967640880074652742780142494579258788820056842838115669472196386865459400540160.000000")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%f", b, "1000000000000000052504760255204420248704468581108159154915854115511802457988908195786371375080447864043704443832883878176942523235360430575644792184786706982848387200926575803737830233794788090059368953234970799945081119038967640880074652742780142494579258788820056842838115669472196386865459400540160.000000"); bad++; }
	snprintf(b, sizeof b, "%.0f", 0.5);
	if (strcmp(b, "0")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%.0f", b, "0"); bad++; }
	snprintf(b, sizeof b, "%.0f", 1.5);
	if (strcmp(b, "2")) { printf("MISMATCH %s: got [%s] want [%s]\n", "%.0f", b, "2"); bad++; }
	printf("B1.0 printf: %d of 20 cases match\n", 20 - bad);
	return bad;
}
