/* GENERATED by gen-b0-strtod.py: B1.0b, musl's narrowed strtod/atof/sscanf against the host. */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int bad;

static void one(const char *s, unsigned long want, long want_end, int want_range)
{
	char *end;
	errno = 0;
	double d = strtod(s, &end);
	int range = errno == ERANGE;
	unsigned long got;
	memcpy(&got, &d, 8);
	if (got != want || end - s != want_end || (want_range >= 0 && range != want_range)) {
		printf("MISMATCH strtod [%s]: bits %016lx end %ld erange %d, want %016lx %ld %d\n",
		       s, got, (long)(end - s), range, want, want_end, want_range);
		bad++;
	}
}

int main(void)
{
	one("0", 0x0000000000000000UL, 1, 0);
	one("-0", 0x8000000000000000UL, 2, 0);
	one("1", 0x3ff0000000000000UL, 1, 0);
	one("-1", 0xbff0000000000000UL, 2, 0);
	one("0.1", 0x3fb999999999999aUL, 3, 0);
	one("3.14159265358979323846", 0x400921fb54442d18UL, 22, 0);
	one("1.5", 0x3ff8000000000000UL, 3, 0);
	one("2.5e-3", 0x3f647ae147ae147bUL, 6, 0);
	one("9007199254740993", 0x4340000000000000UL, 16, 0);
	one("0.30000000000000004", 0x3fd3333333333334UL, 19, 0);
	one("123456789012345678901234567890", 0x45f8ee90ff6c373eUL, 30, 0);
	one("1.7976931348623157e308", 0x7fefffffffffffffUL, 22, 0);
	one("1e309", 0x7ff0000000000000UL, 5, 1);
	one("2.2250738585072014e-308", 0x0010000000000000UL, 23, 0);
	one("4.9406564584124654e-324", 0x0000000000000001UL, 23, -1);
	one("1e-400", 0x0000000000000000UL, 6, 1);
	one("0x1.8p1", 0x4008000000000000UL, 7, 0);
	one("  42.5xyz", 0x4045400000000000UL, 6, 0);
	one("inf", 0x7ff0000000000000UL, 3, 0);
	one("-Infinity", 0xfff0000000000000UL, 9, 0);
	one("6.02214076e23", 0x44dfe185ca57c517UL, 13, 0);
	{
		double d = atof("6.02214076e23");
		unsigned long got;
		memcpy(&got, &d, 8);
		if (got != 0x44dfe185ca57c517UL) { printf("MISMATCH atof: %016lx\n", got); bad++; }
	}
	{
		double d = 0;
		int n = sscanf("x 12.75", "x %lf", &d);
		unsigned long got;
		memcpy(&got, &d, 8);
		if (n != 1 || got != 0x4029800000000000UL) { printf("MISMATCH sscanf: n %d %016lx\n", n, got); bad++; }
	}
	printf("B1.0b strtod: %d of 23 cases match\n", 23 - bad);
	return bad;
}
