# Generate b0-printf.c: each case's expected string is what the HOST's printf produces (glibc), so the oracle is
# independent of the code under test.
import ctypes, sys
libc = ctypes.CDLL(None)
cases = [
    ("%d", "int", -12345), ("%u", "unsigned", 4000000000), ("%x", "unsigned", 0xdeadbeef), ("%08X", "unsigned", 0xbeef),
    ("%ld", "long", -9000000000000), ("%llu", "unsigned long long", 18446744073709551615),
    ("%s|%-8s|", None, None), ("%c%c%c", None, None), ("%5d|%-5d|", None, None),
    ("%f", "double", 3.14159265358979), ("%.3f", "double", -0.0005), ("%e", "double", 6.02214076e23),
    ("%g", "double", 1e-5), ("%g", "double", 123456789.0), ("%.10g", "double", 2.0 / 3.0), ("%10.4f|", "double", 2.5),
    ("%a", "double", 1.0), ("%f", "double", 1e300), ("%.0f", "double", 0.5), ("%.0f", "double", 1.5),
]
def host(fmt, typ, val):
    buf = ctypes.create_string_buffer(512)
    if fmt == "%s|%-8s|": libc.snprintf(buf, 512, fmt.encode(), b"abc", b"de")
    elif fmt == "%c%c%c": libc.snprintf(buf, 512, fmt.encode(), ord("x"), ord("y"), ord("z"))
    elif fmt == "%5d|%-5d|": libc.snprintf(buf, 512, fmt.encode(), 42, 42)
    elif typ == "double": libc.snprintf(buf, 512, fmt.encode(), ctypes.c_double(val))
    elif typ in ("long", "unsigned long long"): libc.snprintf(buf, 512, fmt.encode(), ctypes.c_longlong(val) if typ == "long" else ctypes.c_ulonglong(val))
    else: libc.snprintf(buf, 512, fmt.encode(), ctypes.c_long(val) if typ == "int" else ctypes.c_ulong(val))
    return buf.value.decode()
def cexpr(fmt, typ, val):
    if fmt == "%s|%-8s|": return '"abc", "de"'
    if fmt == "%c%c%c": return "'x', 'y', 'z'"
    if fmt == "%5d|%-5d|": return "42, 42"
    if typ == "double": return repr(val)
    if typ == "unsigned long long": return f"{val}ULL"
    if typ == "long": return f"{val}L"
    if typ == "unsigned": return f"{val}U"
    return str(val)
def cstr(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
out = ['/* B1.0 (docs/plans/b0-silicon-delegated-runtime.md): printf on the gp-captable silicon build. GENERATED by',
       ' * gen_b0_printf.py: each expected string is the HOST printf\'s output for the same call. Exit 0 = every case',
       ' * matched; otherwise the count of mismatches (each printed). */',
       '#include <stdio.h>', '#include <string.h>', '', 'int main(void)', '{', '\tchar b[512];', '\tint bad = 0;']
for fmt, typ, val in cases:
    want = host(fmt, typ, val)
    out.append(f'\tsnprintf(b, sizeof b, {cstr(fmt)}, {cexpr(fmt, typ, val)});')
    out.append(f'\tif (strcmp(b, {cstr(want)})) {{ printf("MISMATCH %s: got [%s] want [%s]\\n", {cstr(fmt)}, b, {cstr(want)}); bad++; }}')
out += [f'\tprintf("B1.0 printf: %d of {len(cases)} cases match\\n", {len(cases)} - bad);', '\treturn bad;', '}', '']
open(sys.argv[1], "w").write("\n".join(out))
print(len(cases), "cases")
