#!/usr/bin/env python3
"""Generate b0-strtod.c (B1.0b): musl's narrowed float parser (gen-floatscan-double.py) against the host's.

Every expected value is the HOST's correctly rounded double for the same text: Python's float() rounds decimal and
hex input to nearest-even exactly as C's strtod must. A case compares the 64-bit pattern (so -0.0, subnormals and
infinities are exact), the end pointer's offset, and errno where C defines it (ERANGE on overflow and underflow).
The app prints one MISMATCH line per failure and exits with their number; 0 is a pass."""
import math
import struct
import sys

# (text, expected end offset, expects ERANGE: True, False, or None = not checked)
CASES = [
    ("0", 1, False), ("-0", 2, False), ("1", 1, False), ("-1", 2, False), ("0.1", 3, False),
    ("3.14159265358979323846", 22, False), ("1.5", 3, False), ("2.5e-3", 6, False),
    ("9007199254740993", 16, False),            # 2^53 + 1: ties to even, 2^53
    ("0.30000000000000004", 19, False), ("123456789012345678901234567890", 30, False),
    ("1.7976931348623157e308", 22, False),      # DBL_MAX
    ("1e309", 5, True),                         # overflow: inf, ERANGE
    ("2.2250738585072014e-308", 23, False),     # DBL_MIN
    # The smallest subnormal. ERANGE on a subnormal result is implementation-defined (C 7.22.1.3): glibc sets it,
    # musl only when its rounding step leaves a fraction (floatscan's `denormal && frac`), which this input does not.
    # Measured in QEMU: musl clears it, glibc sets it. Value and end are checked.
    ("4.9406564584124654e-324", 23, None),
    ("1e-400", 6, True),                        # underflow to 0, ERANGE
    ("0x1.8p1", 7, False),                      # hex: 3.0
    ("  42.5xyz", 6, False),                    # leading space skipped, stops at 'x'
    ("inf", 3, False), ("-Infinity", 9, False),
    ("6.02214076e23", 13, False),
]


def bits(text):
    t = text.strip()
    tail = t
    while tail and tail[-1].isalpha() and tail.lower() not in ("inf", "-inf", "infinity", "-infinity"):
        tail = tail[:-1]
    v = float.fromhex(tail) if "0x" in tail.lower() else float(tail)
    return struct.unpack("<Q", struct.pack("<d", v))[0]


def main(out):
    lines = ["/* GENERATED by gen-b0-strtod.py: B1.0b, musl's narrowed strtod/atof/sscanf against the host. */",
             "#include <errno.h>", "#include <stdio.h>", "#include <stdlib.h>", "#include <string.h>", "",
             "static int bad;", "",
             "static void one(const char *s, unsigned long want, long want_end, int want_range)",
             "{",
             "\tchar *end;", "\terrno = 0;", "\tdouble d = strtod(s, &end);", "\tint range = errno == ERANGE;",
             "\tunsigned long got;", "\tmemcpy(&got, &d, 8);",
             "\tif (got != want || end - s != want_end || (want_range >= 0 && range != want_range)) {",
             "\t\tprintf(\"MISMATCH strtod [%s]: bits %016lx end %ld erange %d, want %016lx %ld %d\\n\",",
             "\t\t       s, got, (long)(end - s), range, want, want_end, want_range);",
             "\t\tbad++;", "\t}", "}", "", "int main(void)", "{"]
    for text, end, rng in CASES:
        lines.append(f"\tone(\"{text}\", 0x{bits(text):016x}UL, {end}, {-1 if rng is None else (1 if rng else 0)});")
    # atof and sscanf("%lf") once each: the other two entries into the same parser
    a = struct.unpack("<Q", struct.pack("<d", float("6.02214076e23")))[0]
    s = struct.unpack("<Q", struct.pack("<d", 12.75))[0]
    lines += ["\t{", "\t\tdouble d = atof(\"6.02214076e23\");", "\t\tunsigned long got;", "\t\tmemcpy(&got, &d, 8);",
              f"\t\tif (got != 0x{a:016x}UL) {{ printf(\"MISMATCH atof: %016lx\\n\", got); bad++; }}", "\t}",
              "\t{", "\t\tdouble d = 0;", "\t\tint n = sscanf(\"x 12.75\", \"x %lf\", &d);", "\t\tunsigned long got;",
              "\t\tmemcpy(&got, &d, 8);",
              f"\t\tif (n != 1 || got != 0x{s:016x}UL) {{ printf(\"MISMATCH sscanf: n %d %016lx\\n\", n, got); bad++; }}",
              "\t}"]
    total = len(CASES) + 2
    lines += [f"\tprintf(\"B1.0b strtod: %d of {total} cases match\\n\", {total} - bad);", "\treturn bad;", "}", ""]
    open(out, "w").write("\n".join(lines))
    print(f"wrote {out}: {total} cases")


if __name__ == "__main__":
    main(sys.argv[1])
