#!/usr/bin/env python3
"""Generate musl's float PARSING without `long double`: floatscan, strtod and vfscanf, narrowed to double.

WHY (B1.0b, docs/plans/b0-silicon-delegated-runtime.md). On the silicon build (gp-captable, full LTO) the per-member
codegen verifier drops musl's src/internal/floatscan.o: its long double needs fp128 constant pools, which
gp-captable refuses (ISSUES C-43). strtod.o and vfscanf.o survive, but both call __floatscan, so any program that
parses a float fails to link -- and memcached does (safe_strtod, atof). vfprintf had the same problem and
gen-vfprintf-double.py solved it the same way; this is its sibling.

WHY THE SUBSTITUTION IS SOUND. musl's floatscan is written for every long double format it supports, and one of
them is long double == double (LDBL_MANT_DIG == 53, LDBL_MAX_EXP == 1024: arm, mips and others). Replacing
`long double` by `double` and every LDBL_ by DBL_ selects exactly that configuration's constants (the #if chain at
the top of the file), so the result is musl's own, correctly rounded double parser, not a reimplementation.

WHAT IT COSTS. strtold is not generated, and scanf's %Lf stores a double. On this target nothing can produce or
consume a long double anyway (C-20). A program that references strtold therefore pulls the archive's strtod.o, whose
strtof/strtod collide with these: a LOUD link error, never a silent mix.

WHY THE INTERNAL NAME CHANGES. The generated parser is __floatscan_d, returning double. An archive member still
expecting the fp128-returning __floatscan finds no definition and fails to link, rather than reading half of a
double as a long double.

LIKE ITS SIBLING, IT FAILS LOUDLY IF UPSTREAM DRIFTS: every rule must fire at least once in its file, and the
leftover check rejects any `long double`, LDBL_ or long-double libm call that survives.
"""

import pathlib
import re
import sys

DECL = "hidden double __floatscan_d(FILE *, int, int);\n"

# (file, [(pattern, replacement, why)]) -- every rule MUST fire in its file.
RULES = {
    "src/internal/floatscan.c": [
        (r"long double", "double", "the parsed value and every intermediate"),
        (r"\bLDBL_", "DBL_", "selects the LDBL_MANT_DIG == 53 configuration and its limits"),
        (r"\bscalbnl\b", "scalbn", "the final scaling"),
        (r"\bfmodl\b", "fmod", "the rounding bias"),
        (r"\bcopysignl\b", "copysign", "the rounding bias"),
        (r"\bfabsl\b", "fabs", "the overflow check"),
        (r"(\b\d+\.\d*(?:[eE][-+]?\d+)?)L\b", r"\1", "long double LITERALS (1000000000.0L): an fp128 constant"),
        (r"\bdouble __floatscan\(", "double __floatscan_d(", "the renamed entry"),
        (r'#include "floatscan.h"\n', '#include "floatscan.h"\n' + DECL, "the entry's declaration"),
    ],
    "src/stdlib/strtod.c": [
        (r"static long double strtox", "static double strtox", "the helper's return type"),
        (r"long double y = __floatscan\(", "double y = __floatscan_d(", "the call"),
        (r"\nlong double strtold\(const char \*restrict s, char \*\*restrict p\)\n\{\n\treturn strtox\(s, p, 2\);\n\}\n",
         "\n", "strtold is not provided (see the header)"),
        (r'#include "floatscan.h"\n', '#include "floatscan.h"\n' + DECL, "the entry's declaration"),
    ],
    "src/stdio/vfscanf.c": [
        (r"\tlong double y;", "\tdouble y;", "the scanned value"),
        (r"y = __floatscan\(", "y = __floatscan_d(", "the call"),
        (r"\*\(long double \*\)dest = y;", "*(double *)dest = y;", "%Lf stores a double (C-20)"),
        (r'#include "floatscan.h"\n', '#include "floatscan.h"\n' + DECL, "the entry's declaration"),
    ],
}
LEFTOVER = re.compile(r"long double|\bLDBL_|\b(scalbnl|fmodl|copysignl|fabsl|frexpl|ldexpl)\b|__floatscan\("
                      r"|\b\d+\.\d*(?:[eE][-+]?\d+)?L\b|\b\d+[eE][-+]?\d+L\b|\b0[xX][0-9a-fA-F.]+[pP][-+]?\d+L\b")


def main(argv):
    if len(argv) != 3:
        sys.exit("usage: gen-floatscan-double.py <musl-src-root> <out-dir>")
    root, out = pathlib.Path(argv[1]), pathlib.Path(argv[2])
    out.mkdir(parents=True, exist_ok=True)
    for rel, rules in RULES.items():
        text = (root / rel).read_text()
        for pat, rep, why in rules:
            text, n = re.subn(pat, rep, text)
            if n == 0:
                sys.exit(f"{rel}: rule {pat!r} ({why}) did not fire -- upstream changed; refusing to generate")
            print(f"{rel}: {pat!r} x{n}")
        bad = [m.group(0) for m in LEFTOVER.finditer(text)]
        if bad:
            sys.exit(f"{rel}: left over after narrowing: {sorted(set(bad))}")
        name = pathlib.Path(rel).stem + "-double.c"
        (out / name).write_text(f"/* GENERATED by gen-floatscan-double.py from musl's {rel}; do not edit. */\n" + text)
    print("ok")


if __name__ == "__main__":
    main(sys.argv)
