# Each component has one release pin; both cached and new archives are verified.
macro(port_read_upstream)
  file(READ "${PROJECT_SOURCE_DIR}/upstream.json" upstream_json)
  foreach(key name version url sha256)
    string(JSON UPSTREAM_${key} GET "${upstream_json}" ${key})
  endforeach()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/upstream.json")
endmacro()

function(port_download archive)
  get_filename_component(download_dir "${archive}" DIRECTORY)
  file(MAKE_DIRECTORY "${download_dir}")
  file(LOCK "${archive}.lock" GUARD FUNCTION TIMEOUT 120)
  if(NOT EXISTS "${archive}")
    file(DOWNLOAD "${UPSTREAM_url}" "${archive}.part"
      TLS_VERIFY ON SHOW_PROGRESS STATUS download_status)
    list(GET download_status 0 download_code)
    if(NOT download_code EQUAL 0)
      file(REMOVE "${archive}.part")
      message(FATAL_ERROR "Upstream download failed: ${download_status}")
    endif()
    file(SHA256 "${archive}.part" actual_sha)
    if(NOT actual_sha STREQUAL UPSTREAM_sha256)
      file(REMOVE "${archive}.part")
      message(FATAL_ERROR "Downloaded archive checksum mismatch: ${archive}")
    endif()
    file(RENAME "${archive}.part" "${archive}")
  endif()
  file(SHA256 "${archive}" actual_sha)
  if(NOT actual_sha STREQUAL UPSTREAM_sha256)
    message(FATAL_ERROR "Cached archive checksum mismatch: ${archive}")
  endif()
endfunction()
