add_subdirectory("${CAPSTONE_REPO_ROOT}/capstone/runtime" "${CMAKE_BINARY_DIR}/runtime")
function(wg_executable name variant workload)
  set(source "${CMAKE_BINARY_DIR}/source-${variant}")
  if(PORT_HOSTED)
    set(platform src/native/main.c src/native/regions.c)
  else()
    set(platform src/capstone-domain/entry.c src/allocators/sublet/regions.c
      "${CAPSTONE_REPO_ROOT}/capstone/benchmarks/beebs/adapted/beebs_freestanding_string.c"
      "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/start.S"
      "${CAPSTONE_REPO_ROOT}/capstone/tests/runtime-qemu/gct-section-end.S")
  endif()
  add_executable(${name} ${platform} ${workload} src/shared/backing.c "${source}/ggml/src/ggml.c")
  add_dependencies(${name} source-${variant})
  target_include_directories(${name} PRIVATE src/shared "${source}/ggml/include")
  target_compile_definitions(${name} PRIVATE GGML_CONTEXT_ONLY NDEBUG)
  target_compile_options(${name} PRIVATE -Wall -Wextra -ffunction-sections -fdata-sections)
  target_link_libraries(${name} PRIVATE Capstone::Runtime)
  if(NOT PORT_HOSTED)
    target_compile_definitions(${name} PRIVATE WG_DOMAIN)
    set(link_script "${CAPSTONE_REPO_ROOT}/capstone/my_first_domain/link.ld")
    target_link_options(${name} PRIVATE --gc-sections -T "${link_script}")
    set_target_properties(${name} PROPERTIES SUFFIX .dom LINK_DEPENDS "${link_script}")
  endif()
endfunction()
if(NOT PORT_HOSTED)
  enable_language(ASM)
endif()
wg_source(ported)
wg_executable(replay ported src/shared/replay.c)
if(PORT_HOSTED)
  add_library(ggml-context STATIC src/native/regions.c src/shared/backing.c
    "${CMAKE_BINARY_DIR}/source-ported/ggml/src/ggml.c")
  add_dependencies(ggml-context source-ported)
  target_include_directories(ggml-context PUBLIC src/shared
    "${CMAKE_BINARY_DIR}/source-ported/ggml/include")
  target_compile_definitions(ggml-context PUBLIC GGML_CONTEXT_ONLY NDEBUG)
  target_link_libraries(ggml-context PUBLIC Capstone::Runtime)
  add_library(Whisper::GgmlContext ALIAS ggml-context)
  add_executable(allocator-example examples/context.c)
  target_link_libraries(allocator-example PRIVATE Whisper::GgmlContext)
  include("${PORT_SUPPORT_ROOT}/cmake/Client.cmake")
  port_add_client(Whisper::GgmlContext)
  wg_source(reference)
  wg_executable(replay-reference reference src/shared/replay.c)
else()
  wg_executable(context-security ported security-tests/shared/lifetimes.c)
endif()
